#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExaminationManagement.Functions.ConnectDatabase
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ExaminationManagement")]
	public partial class ExaminationManagementDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAccount(Account instance);
    partial void UpdateAccount(Account instance);
    partial void DeleteAccount(Account instance);
    partial void InsertTheTest(TheTest instance);
    partial void UpdateTheTest(TheTest instance);
    partial void DeleteTheTest(TheTest instance);
    partial void InsertAccountDetail(AccountDetail instance);
    partial void UpdateAccountDetail(AccountDetail instance);
    partial void DeleteAccountDetail(AccountDetail instance);
    partial void InsertExamineeList(ExamineeList instance);
    partial void UpdateExamineeList(ExamineeList instance);
    partial void DeleteExamineeList(ExamineeList instance);
    partial void InsertExamineeListDetail(ExamineeListDetail instance);
    partial void UpdateExamineeListDetail(ExamineeListDetail instance);
    partial void DeleteExamineeListDetail(ExamineeListDetail instance);
    partial void InsertResult(Result instance);
    partial void UpdateResult(Result instance);
    partial void DeleteResult(Result instance);
    partial void InsertResultDetail(ResultDetail instance);
    partial void UpdateResultDetail(ResultDetail instance);
    partial void DeleteResultDetail(ResultDetail instance);
    partial void InsertTestDetail(TestDetail instance);
    partial void UpdateTestDetail(TestDetail instance);
    partial void DeleteTestDetail(TestDetail instance);
    partial void InsertTestList(TestList instance);
    partial void UpdateTestList(TestList instance);
    partial void DeleteTestList(TestList instance);
    partial void InsertTestListDetail(TestListDetail instance);
    partial void UpdateTestListDetail(TestListDetail instance);
    partial void DeleteTestListDetail(TestListDetail instance);
    partial void InsertTheExamination(TheExamination instance);
    partial void UpdateTheExamination(TheExamination instance);
    partial void DeleteTheExamination(TheExamination instance);
    partial void InsertTheQuestion(TheQuestion instance);
    partial void UpdateTheQuestion(TheQuestion instance);
    partial void DeleteTheQuestion(TheQuestion instance);
    #endregion
		
		public ExaminationManagementDataContext() : 
				base(global::ExaminationManagement.Properties.Settings.Default.ExaminationManagementConnectionString3, mappingSource)
		{
			OnCreated();
		}
		
		public ExaminationManagementDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ExaminationManagementDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ExaminationManagementDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ExaminationManagementDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Account> Accounts
		{
			get
			{
				return this.GetTable<Account>();
			}
		}
		
		public System.Data.Linq.Table<TheTest> TheTests
		{
			get
			{
				return this.GetTable<TheTest>();
			}
		}
		
		public System.Data.Linq.Table<AccountDetail> AccountDetails
		{
			get
			{
				return this.GetTable<AccountDetail>();
			}
		}
		
		public System.Data.Linq.Table<ExamineeList> ExamineeLists
		{
			get
			{
				return this.GetTable<ExamineeList>();
			}
		}
		
		public System.Data.Linq.Table<ExamineeListDetail> ExamineeListDetails
		{
			get
			{
				return this.GetTable<ExamineeListDetail>();
			}
		}
		
		public System.Data.Linq.Table<Result> Results
		{
			get
			{
				return this.GetTable<Result>();
			}
		}
		
		public System.Data.Linq.Table<ResultDetail> ResultDetails
		{
			get
			{
				return this.GetTable<ResultDetail>();
			}
		}
		
		public System.Data.Linq.Table<TestDetail> TestDetails
		{
			get
			{
				return this.GetTable<TestDetail>();
			}
		}
		
		public System.Data.Linq.Table<TestList> TestLists
		{
			get
			{
				return this.GetTable<TestList>();
			}
		}
		
		public System.Data.Linq.Table<TestListDetail> TestListDetails
		{
			get
			{
				return this.GetTable<TestListDetail>();
			}
		}
		
		public System.Data.Linq.Table<TheExamination> TheExaminations
		{
			get
			{
				return this.GetTable<TheExamination>();
			}
		}
		
		public System.Data.Linq.Table<TheQuestion> TheQuestions
		{
			get
			{
				return this.GetTable<TheQuestion>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Account")]
	public partial class Account : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UserID;
		
		private string _Username;
		
		private string _Password;
		
		private int _Permission;
		
		private System.DateTime _RegistryDate;
		
		private EntitySet<ExamineeListDetail> _ExamineeListDetails;
		
		private EntitySet<Result> _Results;
		
		private EntityRef<AccountDetail> _AccountDetail;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIDChanging(int value);
    partial void OnUserIDChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnPermissionChanging(int value);
    partial void OnPermissionChanged();
    partial void OnRegistryDateChanging(System.DateTime value);
    partial void OnRegistryDateChanged();
    #endregion
		
		public Account()
		{
			this._ExamineeListDetails = new EntitySet<ExamineeListDetail>(new Action<ExamineeListDetail>(this.attach_ExamineeListDetails), new Action<ExamineeListDetail>(this.detach_ExamineeListDetails));
			this._Results = new EntitySet<Result>(new Action<Result>(this.attach_Results), new Action<Result>(this.detach_Results));
			this._AccountDetail = default(EntityRef<AccountDetail>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					if (this._AccountDetail.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="Char(100) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Permission", DbType="Int NOT NULL")]
		public int Permission
		{
			get
			{
				return this._Permission;
			}
			set
			{
				if ((this._Permission != value))
				{
					this.OnPermissionChanging(value);
					this.SendPropertyChanging();
					this._Permission = value;
					this.SendPropertyChanged("Permission");
					this.OnPermissionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegistryDate", DbType="DateTime NOT NULL")]
		public System.DateTime RegistryDate
		{
			get
			{
				return this._RegistryDate;
			}
			set
			{
				if ((this._RegistryDate != value))
				{
					this.OnRegistryDateChanging(value);
					this.SendPropertyChanging();
					this._RegistryDate = value;
					this.SendPropertyChanged("RegistryDate");
					this.OnRegistryDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Account_ExamineeListDetail", Storage="_ExamineeListDetails", ThisKey="UserID", OtherKey="UserID")]
		public EntitySet<ExamineeListDetail> ExamineeListDetails
		{
			get
			{
				return this._ExamineeListDetails;
			}
			set
			{
				this._ExamineeListDetails.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Account_Result", Storage="_Results", ThisKey="UserID", OtherKey="UserID")]
		public EntitySet<Result> Results
		{
			get
			{
				return this._Results;
			}
			set
			{
				this._Results.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AccountDetail_Account", Storage="_AccountDetail", ThisKey="UserID", OtherKey="UserID", IsForeignKey=true)]
		public AccountDetail AccountDetail
		{
			get
			{
				return this._AccountDetail.Entity;
			}
			set
			{
				AccountDetail previousValue = this._AccountDetail.Entity;
				if (((previousValue != value) 
							|| (this._AccountDetail.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._AccountDetail.Entity = null;
						previousValue.Account = null;
					}
					this._AccountDetail.Entity = value;
					if ((value != null))
					{
						value.Account = this;
						this._UserID = value.UserID;
					}
					else
					{
						this._UserID = default(int);
					}
					this.SendPropertyChanged("AccountDetail");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ExamineeListDetails(ExamineeListDetail entity)
		{
			this.SendPropertyChanging();
			entity.Account = this;
		}
		
		private void detach_ExamineeListDetails(ExamineeListDetail entity)
		{
			this.SendPropertyChanging();
			entity.Account = null;
		}
		
		private void attach_Results(Result entity)
		{
			this.SendPropertyChanging();
			entity.Account = this;
		}
		
		private void detach_Results(Result entity)
		{
			this.SendPropertyChanging();
			entity.Account = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TheTest")]
	public partial class TheTest : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TestID;
		
		private string _TestName;
		
		private EntitySet<Result> _Results;
		
		private EntitySet<TestDetail> _TestDetails;
		
		private EntitySet<TestListDetail> _TestListDetails;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTestIDChanging(string value);
    partial void OnTestIDChanged();
    partial void OnTestNameChanging(string value);
    partial void OnTestNameChanged();
    #endregion
		
		public TheTest()
		{
			this._Results = new EntitySet<Result>(new Action<Result>(this.attach_Results), new Action<Result>(this.detach_Results));
			this._TestDetails = new EntitySet<TestDetail>(new Action<TestDetail>(this.attach_TestDetails), new Action<TestDetail>(this.detach_TestDetails));
			this._TestListDetails = new EntitySet<TestListDetail>(new Action<TestListDetail>(this.attach_TestListDetails), new Action<TestListDetail>(this.detach_TestListDetails));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TestID", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TestID
		{
			get
			{
				return this._TestID;
			}
			set
			{
				if ((this._TestID != value))
				{
					this.OnTestIDChanging(value);
					this.SendPropertyChanging();
					this._TestID = value;
					this.SendPropertyChanged("TestID");
					this.OnTestIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TestName", DbType="Char(20) NOT NULL", CanBeNull=false)]
		public string TestName
		{
			get
			{
				return this._TestName;
			}
			set
			{
				if ((this._TestName != value))
				{
					this.OnTestNameChanging(value);
					this.SendPropertyChanging();
					this._TestName = value;
					this.SendPropertyChanged("TestName");
					this.OnTestNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TheTest_Result", Storage="_Results", ThisKey="TestID", OtherKey="TestID")]
		public EntitySet<Result> Results
		{
			get
			{
				return this._Results;
			}
			set
			{
				this._Results.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TheTest_TestDetail", Storage="_TestDetails", ThisKey="TestID", OtherKey="TestID")]
		public EntitySet<TestDetail> TestDetails
		{
			get
			{
				return this._TestDetails;
			}
			set
			{
				this._TestDetails.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TheTest_TestListDetail", Storage="_TestListDetails", ThisKey="TestID", OtherKey="TestID")]
		public EntitySet<TestListDetail> TestListDetails
		{
			get
			{
				return this._TestListDetails;
			}
			set
			{
				this._TestListDetails.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Results(Result entity)
		{
			this.SendPropertyChanging();
			entity.TheTest = this;
		}
		
		private void detach_Results(Result entity)
		{
			this.SendPropertyChanging();
			entity.TheTest = null;
		}
		
		private void attach_TestDetails(TestDetail entity)
		{
			this.SendPropertyChanging();
			entity.TheTest = this;
		}
		
		private void detach_TestDetails(TestDetail entity)
		{
			this.SendPropertyChanging();
			entity.TheTest = null;
		}
		
		private void attach_TestListDetails(TestListDetail entity)
		{
			this.SendPropertyChanging();
			entity.TheTest = this;
		}
		
		private void detach_TestListDetails(TestListDetail entity)
		{
			this.SendPropertyChanging();
			entity.TheTest = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AccountDetails")]
	public partial class AccountDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UserID;
		
		private string _Name;
		
		private string _PhoneNumber;
		
		private string _Email;
		
		private System.DateTime _DOB;
		
		private string _Address;
		
		private string _ClassID;
		
		private int _GradeID;
		
		private int _AccountType;
		
		private string _temp;
		
		private EntityRef<Account> _Account;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIDChanging(int value);
    partial void OnUserIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnPhoneNumberChanging(string value);
    partial void OnPhoneNumberChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnDOBChanging(System.DateTime value);
    partial void OnDOBChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnClassIDChanging(string value);
    partial void OnClassIDChanged();
    partial void OnGradeIDChanging(int value);
    partial void OnGradeIDChanged();
    partial void OnAccountTypeChanging(int value);
    partial void OnAccountTypeChanged();
    partial void OntempChanging(string value);
    partial void OntempChanged();
    #endregion
		
		public AccountDetail()
		{
			this._Account = default(EntityRef<Account>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber", DbType="Char(10)")]
		public string PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				if ((this._PhoneNumber != value))
				{
					this.OnPhoneNumberChanging(value);
					this.SendPropertyChanging();
					this._PhoneNumber = value;
					this.SendPropertyChanged("PhoneNumber");
					this.OnPhoneNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="Char(100) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="DateTime NOT NULL")]
		public System.DateTime DOB
		{
			get
			{
				return this._DOB;
			}
			set
			{
				if ((this._DOB != value))
				{
					this.OnDOBChanging(value);
					this.SendPropertyChanging();
					this._DOB = value;
					this.SendPropertyChanged("DOB");
					this.OnDOBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(250)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClassID", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string ClassID
		{
			get
			{
				return this._ClassID;
			}
			set
			{
				if ((this._ClassID != value))
				{
					this.OnClassIDChanging(value);
					this.SendPropertyChanging();
					this._ClassID = value;
					this.SendPropertyChanged("ClassID");
					this.OnClassIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeID", DbType="Int NOT NULL")]
		public int GradeID
		{
			get
			{
				return this._GradeID;
			}
			set
			{
				if ((this._GradeID != value))
				{
					this.OnGradeIDChanging(value);
					this.SendPropertyChanging();
					this._GradeID = value;
					this.SendPropertyChanged("GradeID");
					this.OnGradeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountType", DbType="Int NOT NULL")]
		public int AccountType
		{
			get
			{
				return this._AccountType;
			}
			set
			{
				if ((this._AccountType != value))
				{
					this.OnAccountTypeChanging(value);
					this.SendPropertyChanging();
					this._AccountType = value;
					this.SendPropertyChanged("AccountType");
					this.OnAccountTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_temp", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string temp
		{
			get
			{
				return this._temp;
			}
			set
			{
				if ((this._temp != value))
				{
					this.OntempChanging(value);
					this.SendPropertyChanging();
					this._temp = value;
					this.SendPropertyChanged("temp");
					this.OntempChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AccountDetail_Account", Storage="_Account", ThisKey="UserID", OtherKey="UserID", IsUnique=true, IsForeignKey=false)]
		public Account Account
		{
			get
			{
				return this._Account.Entity;
			}
			set
			{
				Account previousValue = this._Account.Entity;
				if (((previousValue != value) 
							|| (this._Account.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Account.Entity = null;
						previousValue.AccountDetail = null;
					}
					this._Account.Entity = value;
					if ((value != null))
					{
						value.AccountDetail = this;
					}
					this.SendPropertyChanged("Account");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ExamineeList")]
	public partial class ExamineeList : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ExamineeListID;
		
		private string _ExamineeListName;
		
		private EntitySet<ExamineeListDetail> _ExamineeListDetails;
		
		private EntitySet<TheExamination> _TheExaminations;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnExamineeListIDChanging(int value);
    partial void OnExamineeListIDChanged();
    partial void OnExamineeListNameChanging(string value);
    partial void OnExamineeListNameChanged();
    #endregion
		
		public ExamineeList()
		{
			this._ExamineeListDetails = new EntitySet<ExamineeListDetail>(new Action<ExamineeListDetail>(this.attach_ExamineeListDetails), new Action<ExamineeListDetail>(this.detach_ExamineeListDetails));
			this._TheExaminations = new EntitySet<TheExamination>(new Action<TheExamination>(this.attach_TheExaminations), new Action<TheExamination>(this.detach_TheExaminations));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExamineeListID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ExamineeListID
		{
			get
			{
				return this._ExamineeListID;
			}
			set
			{
				if ((this._ExamineeListID != value))
				{
					this.OnExamineeListIDChanging(value);
					this.SendPropertyChanging();
					this._ExamineeListID = value;
					this.SendPropertyChanged("ExamineeListID");
					this.OnExamineeListIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExamineeListName", DbType="Char(20) NOT NULL", CanBeNull=false)]
		public string ExamineeListName
		{
			get
			{
				return this._ExamineeListName;
			}
			set
			{
				if ((this._ExamineeListName != value))
				{
					this.OnExamineeListNameChanging(value);
					this.SendPropertyChanging();
					this._ExamineeListName = value;
					this.SendPropertyChanged("ExamineeListName");
					this.OnExamineeListNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ExamineeList_ExamineeListDetail", Storage="_ExamineeListDetails", ThisKey="ExamineeListID", OtherKey="ExamineeListID")]
		public EntitySet<ExamineeListDetail> ExamineeListDetails
		{
			get
			{
				return this._ExamineeListDetails;
			}
			set
			{
				this._ExamineeListDetails.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ExamineeList_TheExamination", Storage="_TheExaminations", ThisKey="ExamineeListID", OtherKey="ExamineeListID")]
		public EntitySet<TheExamination> TheExaminations
		{
			get
			{
				return this._TheExaminations;
			}
			set
			{
				this._TheExaminations.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ExamineeListDetails(ExamineeListDetail entity)
		{
			this.SendPropertyChanging();
			entity.ExamineeList = this;
		}
		
		private void detach_ExamineeListDetails(ExamineeListDetail entity)
		{
			this.SendPropertyChanging();
			entity.ExamineeList = null;
		}
		
		private void attach_TheExaminations(TheExamination entity)
		{
			this.SendPropertyChanging();
			entity.ExamineeList = this;
		}
		
		private void detach_TheExaminations(TheExamination entity)
		{
			this.SendPropertyChanging();
			entity.ExamineeList = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ExamineeListDetails")]
	public partial class ExamineeListDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ExamineeListID;
		
		private int _UserID;
		
		private int _Status;
		
		private EntityRef<Account> _Account;
		
		private EntityRef<ExamineeList> _ExamineeList;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnExamineeListIDChanging(int value);
    partial void OnExamineeListIDChanged();
    partial void OnUserIDChanging(int value);
    partial void OnUserIDChanged();
    partial void OnStatusChanging(int value);
    partial void OnStatusChanged();
    #endregion
		
		public ExamineeListDetail()
		{
			this._Account = default(EntityRef<Account>);
			this._ExamineeList = default(EntityRef<ExamineeList>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExamineeListID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ExamineeListID
		{
			get
			{
				return this._ExamineeListID;
			}
			set
			{
				if ((this._ExamineeListID != value))
				{
					if (this._ExamineeList.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnExamineeListIDChanging(value);
					this.SendPropertyChanging();
					this._ExamineeListID = value;
					this.SendPropertyChanged("ExamineeListID");
					this.OnExamineeListIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					if (this._Account.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int NOT NULL")]
		public int Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Account_ExamineeListDetail", Storage="_Account", ThisKey="UserID", OtherKey="UserID", IsForeignKey=true)]
		public Account Account
		{
			get
			{
				return this._Account.Entity;
			}
			set
			{
				Account previousValue = this._Account.Entity;
				if (((previousValue != value) 
							|| (this._Account.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Account.Entity = null;
						previousValue.ExamineeListDetails.Remove(this);
					}
					this._Account.Entity = value;
					if ((value != null))
					{
						value.ExamineeListDetails.Add(this);
						this._UserID = value.UserID;
					}
					else
					{
						this._UserID = default(int);
					}
					this.SendPropertyChanged("Account");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ExamineeList_ExamineeListDetail", Storage="_ExamineeList", ThisKey="ExamineeListID", OtherKey="ExamineeListID", IsForeignKey=true)]
		public ExamineeList ExamineeList
		{
			get
			{
				return this._ExamineeList.Entity;
			}
			set
			{
				ExamineeList previousValue = this._ExamineeList.Entity;
				if (((previousValue != value) 
							|| (this._ExamineeList.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ExamineeList.Entity = null;
						previousValue.ExamineeListDetails.Remove(this);
					}
					this._ExamineeList.Entity = value;
					if ((value != null))
					{
						value.ExamineeListDetails.Add(this);
						this._ExamineeListID = value.ExamineeListID;
					}
					else
					{
						this._ExamineeListID = default(int);
					}
					this.SendPropertyChanged("ExamineeList");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Result")]
	public partial class Result : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ResultID;
		
		private int _UserID;
		
		private string _TestID;
		
		private int _TotalScore;
		
		private EntitySet<ResultDetail> _ResultDetails;
		
		private EntityRef<Account> _Account;
		
		private EntityRef<TheTest> _TheTest;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnResultIDChanging(int value);
    partial void OnResultIDChanged();
    partial void OnUserIDChanging(int value);
    partial void OnUserIDChanged();
    partial void OnTestIDChanging(string value);
    partial void OnTestIDChanged();
    partial void OnTotalScoreChanging(int value);
    partial void OnTotalScoreChanged();
    #endregion
		
		public Result()
		{
			this._ResultDetails = new EntitySet<ResultDetail>(new Action<ResultDetail>(this.attach_ResultDetails), new Action<ResultDetail>(this.detach_ResultDetails));
			this._Account = default(EntityRef<Account>);
			this._TheTest = default(EntityRef<TheTest>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResultID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ResultID
		{
			get
			{
				return this._ResultID;
			}
			set
			{
				if ((this._ResultID != value))
				{
					this.OnResultIDChanging(value);
					this.SendPropertyChanging();
					this._ResultID = value;
					this.SendPropertyChanged("ResultID");
					this.OnResultIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int NOT NULL")]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					if (this._Account.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TestID", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string TestID
		{
			get
			{
				return this._TestID;
			}
			set
			{
				if ((this._TestID != value))
				{
					if (this._TheTest.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTestIDChanging(value);
					this.SendPropertyChanging();
					this._TestID = value;
					this.SendPropertyChanged("TestID");
					this.OnTestIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalScore", DbType="Int NOT NULL")]
		public int TotalScore
		{
			get
			{
				return this._TotalScore;
			}
			set
			{
				if ((this._TotalScore != value))
				{
					this.OnTotalScoreChanging(value);
					this.SendPropertyChanging();
					this._TotalScore = value;
					this.SendPropertyChanged("TotalScore");
					this.OnTotalScoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Result_ResultDetail", Storage="_ResultDetails", ThisKey="ResultID", OtherKey="ResultID")]
		public EntitySet<ResultDetail> ResultDetails
		{
			get
			{
				return this._ResultDetails;
			}
			set
			{
				this._ResultDetails.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Account_Result", Storage="_Account", ThisKey="UserID", OtherKey="UserID", IsForeignKey=true)]
		public Account Account
		{
			get
			{
				return this._Account.Entity;
			}
			set
			{
				Account previousValue = this._Account.Entity;
				if (((previousValue != value) 
							|| (this._Account.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Account.Entity = null;
						previousValue.Results.Remove(this);
					}
					this._Account.Entity = value;
					if ((value != null))
					{
						value.Results.Add(this);
						this._UserID = value.UserID;
					}
					else
					{
						this._UserID = default(int);
					}
					this.SendPropertyChanged("Account");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TheTest_Result", Storage="_TheTest", ThisKey="TestID", OtherKey="TestID", IsForeignKey=true)]
		public TheTest TheTest
		{
			get
			{
				return this._TheTest.Entity;
			}
			set
			{
				TheTest previousValue = this._TheTest.Entity;
				if (((previousValue != value) 
							|| (this._TheTest.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TheTest.Entity = null;
						previousValue.Results.Remove(this);
					}
					this._TheTest.Entity = value;
					if ((value != null))
					{
						value.Results.Add(this);
						this._TestID = value.TestID;
					}
					else
					{
						this._TestID = default(string);
					}
					this.SendPropertyChanged("TheTest");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ResultDetails(ResultDetail entity)
		{
			this.SendPropertyChanging();
			entity.Result = this;
		}
		
		private void detach_ResultDetails(ResultDetail entity)
		{
			this.SendPropertyChanging();
			entity.Result = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ResultDetails")]
	public partial class ResultDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ResultDetailsID;
		
		private int _QuestionID;
		
		private int _ResultID;
		
		private string _Answer;
		
		private int _Score;
		
		private EntityRef<Result> _Result;
		
		private EntityRef<TheQuestion> _TheQuestion;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnResultDetailsIDChanging(int value);
    partial void OnResultDetailsIDChanged();
    partial void OnQuestionIDChanging(int value);
    partial void OnQuestionIDChanged();
    partial void OnResultIDChanging(int value);
    partial void OnResultIDChanged();
    partial void OnAnswerChanging(string value);
    partial void OnAnswerChanged();
    partial void OnScoreChanging(int value);
    partial void OnScoreChanged();
    #endregion
		
		public ResultDetail()
		{
			this._Result = default(EntityRef<Result>);
			this._TheQuestion = default(EntityRef<TheQuestion>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResultDetailsID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ResultDetailsID
		{
			get
			{
				return this._ResultDetailsID;
			}
			set
			{
				if ((this._ResultDetailsID != value))
				{
					this.OnResultDetailsIDChanging(value);
					this.SendPropertyChanging();
					this._ResultDetailsID = value;
					this.SendPropertyChanged("ResultDetailsID");
					this.OnResultDetailsIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuestionID", DbType="Int NOT NULL")]
		public int QuestionID
		{
			get
			{
				return this._QuestionID;
			}
			set
			{
				if ((this._QuestionID != value))
				{
					if (this._TheQuestion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnQuestionIDChanging(value);
					this.SendPropertyChanging();
					this._QuestionID = value;
					this.SendPropertyChanged("QuestionID");
					this.OnQuestionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResultID", DbType="Int NOT NULL")]
		public int ResultID
		{
			get
			{
				return this._ResultID;
			}
			set
			{
				if ((this._ResultID != value))
				{
					if (this._Result.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnResultIDChanging(value);
					this.SendPropertyChanging();
					this._ResultID = value;
					this.SendPropertyChanged("ResultID");
					this.OnResultIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Answer", DbType="Char(20) NOT NULL", CanBeNull=false)]
		public string Answer
		{
			get
			{
				return this._Answer;
			}
			set
			{
				if ((this._Answer != value))
				{
					this.OnAnswerChanging(value);
					this.SendPropertyChanging();
					this._Answer = value;
					this.SendPropertyChanged("Answer");
					this.OnAnswerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Score", DbType="Int NOT NULL")]
		public int Score
		{
			get
			{
				return this._Score;
			}
			set
			{
				if ((this._Score != value))
				{
					this.OnScoreChanging(value);
					this.SendPropertyChanging();
					this._Score = value;
					this.SendPropertyChanged("Score");
					this.OnScoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Result_ResultDetail", Storage="_Result", ThisKey="ResultID", OtherKey="ResultID", IsForeignKey=true)]
		public Result Result
		{
			get
			{
				return this._Result.Entity;
			}
			set
			{
				Result previousValue = this._Result.Entity;
				if (((previousValue != value) 
							|| (this._Result.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Result.Entity = null;
						previousValue.ResultDetails.Remove(this);
					}
					this._Result.Entity = value;
					if ((value != null))
					{
						value.ResultDetails.Add(this);
						this._ResultID = value.ResultID;
					}
					else
					{
						this._ResultID = default(int);
					}
					this.SendPropertyChanged("Result");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TheQuestion_ResultDetail", Storage="_TheQuestion", ThisKey="QuestionID", OtherKey="QuestionID", IsForeignKey=true)]
		public TheQuestion TheQuestion
		{
			get
			{
				return this._TheQuestion.Entity;
			}
			set
			{
				TheQuestion previousValue = this._TheQuestion.Entity;
				if (((previousValue != value) 
							|| (this._TheQuestion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TheQuestion.Entity = null;
						previousValue.ResultDetails.Remove(this);
					}
					this._TheQuestion.Entity = value;
					if ((value != null))
					{
						value.ResultDetails.Add(this);
						this._QuestionID = value.QuestionID;
					}
					else
					{
						this._QuestionID = default(int);
					}
					this.SendPropertyChanged("TheQuestion");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TestDetails")]
	public partial class TestDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TestID;
		
		private int _QuestionID;
		
		private EntityRef<TheTest> _TheTest;
		
		private EntityRef<TheQuestion> _TheQuestion;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTestIDChanging(string value);
    partial void OnTestIDChanged();
    partial void OnQuestionIDChanging(int value);
    partial void OnQuestionIDChanged();
    #endregion
		
		public TestDetail()
		{
			this._TheTest = default(EntityRef<TheTest>);
			this._TheQuestion = default(EntityRef<TheQuestion>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TestID", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TestID
		{
			get
			{
				return this._TestID;
			}
			set
			{
				if ((this._TestID != value))
				{
					if (this._TheTest.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTestIDChanging(value);
					this.SendPropertyChanging();
					this._TestID = value;
					this.SendPropertyChanged("TestID");
					this.OnTestIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuestionID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int QuestionID
		{
			get
			{
				return this._QuestionID;
			}
			set
			{
				if ((this._QuestionID != value))
				{
					if (this._TheQuestion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnQuestionIDChanging(value);
					this.SendPropertyChanging();
					this._QuestionID = value;
					this.SendPropertyChanged("QuestionID");
					this.OnQuestionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TheTest_TestDetail", Storage="_TheTest", ThisKey="TestID", OtherKey="TestID", IsForeignKey=true)]
		public TheTest TheTest
		{
			get
			{
				return this._TheTest.Entity;
			}
			set
			{
				TheTest previousValue = this._TheTest.Entity;
				if (((previousValue != value) 
							|| (this._TheTest.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TheTest.Entity = null;
						previousValue.TestDetails.Remove(this);
					}
					this._TheTest.Entity = value;
					if ((value != null))
					{
						value.TestDetails.Add(this);
						this._TestID = value.TestID;
					}
					else
					{
						this._TestID = default(string);
					}
					this.SendPropertyChanged("TheTest");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TheQuestion_TestDetail", Storage="_TheQuestion", ThisKey="QuestionID", OtherKey="QuestionID", IsForeignKey=true)]
		public TheQuestion TheQuestion
		{
			get
			{
				return this._TheQuestion.Entity;
			}
			set
			{
				TheQuestion previousValue = this._TheQuestion.Entity;
				if (((previousValue != value) 
							|| (this._TheQuestion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TheQuestion.Entity = null;
						previousValue.TestDetails.Remove(this);
					}
					this._TheQuestion.Entity = value;
					if ((value != null))
					{
						value.TestDetails.Add(this);
						this._QuestionID = value.QuestionID;
					}
					else
					{
						this._QuestionID = default(int);
					}
					this.SendPropertyChanged("TheQuestion");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TestList")]
	public partial class TestList : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TestListID;
		
		private string _TestListName;
		
		private EntitySet<TestListDetail> _TestListDetails;
		
		private EntitySet<TheExamination> _TheExaminations;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTestListIDChanging(string value);
    partial void OnTestListIDChanged();
    partial void OnTestListNameChanging(string value);
    partial void OnTestListNameChanged();
    #endregion
		
		public TestList()
		{
			this._TestListDetails = new EntitySet<TestListDetail>(new Action<TestListDetail>(this.attach_TestListDetails), new Action<TestListDetail>(this.detach_TestListDetails));
			this._TheExaminations = new EntitySet<TheExamination>(new Action<TheExamination>(this.attach_TheExaminations), new Action<TheExamination>(this.detach_TheExaminations));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TestListID", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TestListID
		{
			get
			{
				return this._TestListID;
			}
			set
			{
				if ((this._TestListID != value))
				{
					this.OnTestListIDChanging(value);
					this.SendPropertyChanging();
					this._TestListID = value;
					this.SendPropertyChanged("TestListID");
					this.OnTestListIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TestListName", DbType="Char(20) NOT NULL", CanBeNull=false)]
		public string TestListName
		{
			get
			{
				return this._TestListName;
			}
			set
			{
				if ((this._TestListName != value))
				{
					this.OnTestListNameChanging(value);
					this.SendPropertyChanging();
					this._TestListName = value;
					this.SendPropertyChanged("TestListName");
					this.OnTestListNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TestList_TestListDetail", Storage="_TestListDetails", ThisKey="TestListID", OtherKey="TestListID")]
		public EntitySet<TestListDetail> TestListDetails
		{
			get
			{
				return this._TestListDetails;
			}
			set
			{
				this._TestListDetails.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TestList_TheExamination", Storage="_TheExaminations", ThisKey="TestListID", OtherKey="TestListID")]
		public EntitySet<TheExamination> TheExaminations
		{
			get
			{
				return this._TheExaminations;
			}
			set
			{
				this._TheExaminations.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TestListDetails(TestListDetail entity)
		{
			this.SendPropertyChanging();
			entity.TestList = this;
		}
		
		private void detach_TestListDetails(TestListDetail entity)
		{
			this.SendPropertyChanging();
			entity.TestList = null;
		}
		
		private void attach_TheExaminations(TheExamination entity)
		{
			this.SendPropertyChanging();
			entity.TestList = this;
		}
		
		private void detach_TheExaminations(TheExamination entity)
		{
			this.SendPropertyChanging();
			entity.TestList = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TestListDetails")]
	public partial class TestListDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TestListID;
		
		private string _TestID;
		
		private EntityRef<TestList> _TestList;
		
		private EntityRef<TheTest> _TheTest;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTestListIDChanging(string value);
    partial void OnTestListIDChanged();
    partial void OnTestIDChanging(string value);
    partial void OnTestIDChanged();
    #endregion
		
		public TestListDetail()
		{
			this._TestList = default(EntityRef<TestList>);
			this._TheTest = default(EntityRef<TheTest>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TestListID", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TestListID
		{
			get
			{
				return this._TestListID;
			}
			set
			{
				if ((this._TestListID != value))
				{
					if (this._TestList.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTestListIDChanging(value);
					this.SendPropertyChanging();
					this._TestListID = value;
					this.SendPropertyChanged("TestListID");
					this.OnTestListIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TestID", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TestID
		{
			get
			{
				return this._TestID;
			}
			set
			{
				if ((this._TestID != value))
				{
					if (this._TheTest.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTestIDChanging(value);
					this.SendPropertyChanging();
					this._TestID = value;
					this.SendPropertyChanged("TestID");
					this.OnTestIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TestList_TestListDetail", Storage="_TestList", ThisKey="TestListID", OtherKey="TestListID", IsForeignKey=true)]
		public TestList TestList
		{
			get
			{
				return this._TestList.Entity;
			}
			set
			{
				TestList previousValue = this._TestList.Entity;
				if (((previousValue != value) 
							|| (this._TestList.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TestList.Entity = null;
						previousValue.TestListDetails.Remove(this);
					}
					this._TestList.Entity = value;
					if ((value != null))
					{
						value.TestListDetails.Add(this);
						this._TestListID = value.TestListID;
					}
					else
					{
						this._TestListID = default(string);
					}
					this.SendPropertyChanged("TestList");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TheTest_TestListDetail", Storage="_TheTest", ThisKey="TestID", OtherKey="TestID", IsForeignKey=true)]
		public TheTest TheTest
		{
			get
			{
				return this._TheTest.Entity;
			}
			set
			{
				TheTest previousValue = this._TheTest.Entity;
				if (((previousValue != value) 
							|| (this._TheTest.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TheTest.Entity = null;
						previousValue.TestListDetails.Remove(this);
					}
					this._TheTest.Entity = value;
					if ((value != null))
					{
						value.TestListDetails.Add(this);
						this._TestID = value.TestID;
					}
					else
					{
						this._TestID = default(string);
					}
					this.SendPropertyChanged("TheTest");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TheExamination")]
	public partial class TheExamination : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ExaminationID;
		
		private string _TestListID;
		
		private System.Nullable<int> _ExamineeListID;
		
		private string _ExaminationName;
		
		private int _ExaminationType;
		
		private int _GradeID;
		
		private int _Time;
		
		private string _Creator;
		
		private System.DateTime _CreateDate;
		
		private System.Nullable<System.DateTime> _StartDate;
		
		private System.Nullable<System.DateTime> _EndDate;
		
		private EntityRef<ExamineeList> _ExamineeList;
		
		private EntityRef<TestList> _TestList;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnExaminationIDChanging(int value);
    partial void OnExaminationIDChanged();
    partial void OnTestListIDChanging(string value);
    partial void OnTestListIDChanged();
    partial void OnExamineeListIDChanging(System.Nullable<int> value);
    partial void OnExamineeListIDChanged();
    partial void OnExaminationNameChanging(string value);
    partial void OnExaminationNameChanged();
    partial void OnExaminationTypeChanging(int value);
    partial void OnExaminationTypeChanged();
    partial void OnGradeIDChanging(int value);
    partial void OnGradeIDChanged();
    partial void OnTimeChanging(int value);
    partial void OnTimeChanged();
    partial void OnCreatorChanging(string value);
    partial void OnCreatorChanged();
    partial void OnCreateDateChanging(System.DateTime value);
    partial void OnCreateDateChanged();
    partial void OnStartDateChanging(System.Nullable<System.DateTime> value);
    partial void OnStartDateChanged();
    partial void OnEndDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEndDateChanged();
    #endregion
		
		public TheExamination()
		{
			this._ExamineeList = default(EntityRef<ExamineeList>);
			this._TestList = default(EntityRef<TestList>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExaminationID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ExaminationID
		{
			get
			{
				return this._ExaminationID;
			}
			set
			{
				if ((this._ExaminationID != value))
				{
					this.OnExaminationIDChanging(value);
					this.SendPropertyChanging();
					this._ExaminationID = value;
					this.SendPropertyChanged("ExaminationID");
					this.OnExaminationIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TestListID", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string TestListID
		{
			get
			{
				return this._TestListID;
			}
			set
			{
				if ((this._TestListID != value))
				{
					if (this._TestList.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTestListIDChanging(value);
					this.SendPropertyChanging();
					this._TestListID = value;
					this.SendPropertyChanged("TestListID");
					this.OnTestListIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExamineeListID", DbType="Int")]
		public System.Nullable<int> ExamineeListID
		{
			get
			{
				return this._ExamineeListID;
			}
			set
			{
				if ((this._ExamineeListID != value))
				{
					if (this._ExamineeList.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnExamineeListIDChanging(value);
					this.SendPropertyChanging();
					this._ExamineeListID = value;
					this.SendPropertyChanged("ExamineeListID");
					this.OnExamineeListIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExaminationName", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string ExaminationName
		{
			get
			{
				return this._ExaminationName;
			}
			set
			{
				if ((this._ExaminationName != value))
				{
					this.OnExaminationNameChanging(value);
					this.SendPropertyChanging();
					this._ExaminationName = value;
					this.SendPropertyChanged("ExaminationName");
					this.OnExaminationNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExaminationType", DbType="Int NOT NULL")]
		public int ExaminationType
		{
			get
			{
				return this._ExaminationType;
			}
			set
			{
				if ((this._ExaminationType != value))
				{
					this.OnExaminationTypeChanging(value);
					this.SendPropertyChanging();
					this._ExaminationType = value;
					this.SendPropertyChanged("ExaminationType");
					this.OnExaminationTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeID", DbType="Int NOT NULL")]
		public int GradeID
		{
			get
			{
				return this._GradeID;
			}
			set
			{
				if ((this._GradeID != value))
				{
					this.OnGradeIDChanging(value);
					this.SendPropertyChanging();
					this._GradeID = value;
					this.SendPropertyChanged("GradeID");
					this.OnGradeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Time", DbType="Int NOT NULL")]
		public int Time
		{
			get
			{
				return this._Time;
			}
			set
			{
				if ((this._Time != value))
				{
					this.OnTimeChanging(value);
					this.SendPropertyChanging();
					this._Time = value;
					this.SendPropertyChanged("Time");
					this.OnTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Creator", DbType="Char(30) NOT NULL", CanBeNull=false)]
		public string Creator
		{
			get
			{
				return this._Creator;
			}
			set
			{
				if ((this._Creator != value))
				{
					this.OnCreatorChanging(value);
					this.SendPropertyChanging();
					this._Creator = value;
					this.SendPropertyChanged("Creator");
					this.OnCreatorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime NOT NULL")]
		public System.DateTime CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> StartDate
		{
			get
			{
				return this._StartDate;
			}
			set
			{
				if ((this._StartDate != value))
				{
					this.OnStartDateChanging(value);
					this.SendPropertyChanging();
					this._StartDate = value;
					this.SendPropertyChanged("StartDate");
					this.OnStartDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EndDate
		{
			get
			{
				return this._EndDate;
			}
			set
			{
				if ((this._EndDate != value))
				{
					this.OnEndDateChanging(value);
					this.SendPropertyChanging();
					this._EndDate = value;
					this.SendPropertyChanged("EndDate");
					this.OnEndDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ExamineeList_TheExamination", Storage="_ExamineeList", ThisKey="ExamineeListID", OtherKey="ExamineeListID", IsForeignKey=true)]
		public ExamineeList ExamineeList
		{
			get
			{
				return this._ExamineeList.Entity;
			}
			set
			{
				ExamineeList previousValue = this._ExamineeList.Entity;
				if (((previousValue != value) 
							|| (this._ExamineeList.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ExamineeList.Entity = null;
						previousValue.TheExaminations.Remove(this);
					}
					this._ExamineeList.Entity = value;
					if ((value != null))
					{
						value.TheExaminations.Add(this);
						this._ExamineeListID = value.ExamineeListID;
					}
					else
					{
						this._ExamineeListID = default(Nullable<int>);
					}
					this.SendPropertyChanged("ExamineeList");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TestList_TheExamination", Storage="_TestList", ThisKey="TestListID", OtherKey="TestListID", IsForeignKey=true)]
		public TestList TestList
		{
			get
			{
				return this._TestList.Entity;
			}
			set
			{
				TestList previousValue = this._TestList.Entity;
				if (((previousValue != value) 
							|| (this._TestList.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TestList.Entity = null;
						previousValue.TheExaminations.Remove(this);
					}
					this._TestList.Entity = value;
					if ((value != null))
					{
						value.TheExaminations.Add(this);
						this._TestListID = value.TestListID;
					}
					else
					{
						this._TestListID = default(string);
					}
					this.SendPropertyChanged("TestList");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TheQuestion")]
	public partial class TheQuestion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _QuestionID;
		
		private int _QuestionLevel;
		
		private int _QuestionType;
		
		private string _QuestionContent;
		
		private string _ChoiceA;
		
		private string _ChoiceB;
		
		private string _ChoiceC;
		
		private string _ChoiceD;
		
		private string _ChoiceE;
		
		private string _ChoiceF;
		
		private string _Answer;
		
		private int _Status;
		
		private System.Nullable<int> _UserID;
		
		private EntitySet<ResultDetail> _ResultDetails;
		
		private EntitySet<TestDetail> _TestDetails;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnQuestionIDChanging(int value);
    partial void OnQuestionIDChanged();
    partial void OnQuestionLevelChanging(int value);
    partial void OnQuestionLevelChanged();
    partial void OnQuestionTypeChanging(int value);
    partial void OnQuestionTypeChanged();
    partial void OnQuestionContentChanging(string value);
    partial void OnQuestionContentChanged();
    partial void OnChoiceAChanging(string value);
    partial void OnChoiceAChanged();
    partial void OnChoiceBChanging(string value);
    partial void OnChoiceBChanged();
    partial void OnChoiceCChanging(string value);
    partial void OnChoiceCChanged();
    partial void OnChoiceDChanging(string value);
    partial void OnChoiceDChanged();
    partial void OnChoiceEChanging(string value);
    partial void OnChoiceEChanged();
    partial void OnChoiceFChanging(string value);
    partial void OnChoiceFChanged();
    partial void OnAnswerChanging(string value);
    partial void OnAnswerChanged();
    partial void OnStatusChanging(int value);
    partial void OnStatusChanged();
    partial void OnUserIDChanging(System.Nullable<int> value);
    partial void OnUserIDChanged();
    #endregion
		
		public TheQuestion()
		{
			this._ResultDetails = new EntitySet<ResultDetail>(new Action<ResultDetail>(this.attach_ResultDetails), new Action<ResultDetail>(this.detach_ResultDetails));
			this._TestDetails = new EntitySet<TestDetail>(new Action<TestDetail>(this.attach_TestDetails), new Action<TestDetail>(this.detach_TestDetails));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuestionID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int QuestionID
		{
			get
			{
				return this._QuestionID;
			}
			set
			{
				if ((this._QuestionID != value))
				{
					this.OnQuestionIDChanging(value);
					this.SendPropertyChanging();
					this._QuestionID = value;
					this.SendPropertyChanged("QuestionID");
					this.OnQuestionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuestionLevel", DbType="Int NOT NULL")]
		public int QuestionLevel
		{
			get
			{
				return this._QuestionLevel;
			}
			set
			{
				if ((this._QuestionLevel != value))
				{
					this.OnQuestionLevelChanging(value);
					this.SendPropertyChanging();
					this._QuestionLevel = value;
					this.SendPropertyChanged("QuestionLevel");
					this.OnQuestionLevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuestionType", DbType="Int NOT NULL")]
		public int QuestionType
		{
			get
			{
				return this._QuestionType;
			}
			set
			{
				if ((this._QuestionType != value))
				{
					this.OnQuestionTypeChanging(value);
					this.SendPropertyChanging();
					this._QuestionType = value;
					this.SendPropertyChanged("QuestionType");
					this.OnQuestionTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuestionContent", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string QuestionContent
		{
			get
			{
				return this._QuestionContent;
			}
			set
			{
				if ((this._QuestionContent != value))
				{
					this.OnQuestionContentChanging(value);
					this.SendPropertyChanging();
					this._QuestionContent = value;
					this.SendPropertyChanged("QuestionContent");
					this.OnQuestionContentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChoiceA", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string ChoiceA
		{
			get
			{
				return this._ChoiceA;
			}
			set
			{
				if ((this._ChoiceA != value))
				{
					this.OnChoiceAChanging(value);
					this.SendPropertyChanging();
					this._ChoiceA = value;
					this.SendPropertyChanged("ChoiceA");
					this.OnChoiceAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChoiceB", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string ChoiceB
		{
			get
			{
				return this._ChoiceB;
			}
			set
			{
				if ((this._ChoiceB != value))
				{
					this.OnChoiceBChanging(value);
					this.SendPropertyChanging();
					this._ChoiceB = value;
					this.SendPropertyChanged("ChoiceB");
					this.OnChoiceBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChoiceC", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string ChoiceC
		{
			get
			{
				return this._ChoiceC;
			}
			set
			{
				if ((this._ChoiceC != value))
				{
					this.OnChoiceCChanging(value);
					this.SendPropertyChanging();
					this._ChoiceC = value;
					this.SendPropertyChanged("ChoiceC");
					this.OnChoiceCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChoiceD", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string ChoiceD
		{
			get
			{
				return this._ChoiceD;
			}
			set
			{
				if ((this._ChoiceD != value))
				{
					this.OnChoiceDChanging(value);
					this.SendPropertyChanging();
					this._ChoiceD = value;
					this.SendPropertyChanged("ChoiceD");
					this.OnChoiceDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChoiceE", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string ChoiceE
		{
			get
			{
				return this._ChoiceE;
			}
			set
			{
				if ((this._ChoiceE != value))
				{
					this.OnChoiceEChanging(value);
					this.SendPropertyChanging();
					this._ChoiceE = value;
					this.SendPropertyChanged("ChoiceE");
					this.OnChoiceEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChoiceF", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string ChoiceF
		{
			get
			{
				return this._ChoiceF;
			}
			set
			{
				if ((this._ChoiceF != value))
				{
					this.OnChoiceFChanging(value);
					this.SendPropertyChanging();
					this._ChoiceF = value;
					this.SendPropertyChanged("ChoiceF");
					this.OnChoiceFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Answer", DbType="Char(20) NOT NULL", CanBeNull=false)]
		public string Answer
		{
			get
			{
				return this._Answer;
			}
			set
			{
				if ((this._Answer != value))
				{
					this.OnAnswerChanging(value);
					this.SendPropertyChanging();
					this._Answer = value;
					this.SendPropertyChanged("Answer");
					this.OnAnswerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int NOT NULL")]
		public int Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int")]
		public System.Nullable<int> UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TheQuestion_ResultDetail", Storage="_ResultDetails", ThisKey="QuestionID", OtherKey="QuestionID")]
		public EntitySet<ResultDetail> ResultDetails
		{
			get
			{
				return this._ResultDetails;
			}
			set
			{
				this._ResultDetails.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TheQuestion_TestDetail", Storage="_TestDetails", ThisKey="QuestionID", OtherKey="QuestionID")]
		public EntitySet<TestDetail> TestDetails
		{
			get
			{
				return this._TestDetails;
			}
			set
			{
				this._TestDetails.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ResultDetails(ResultDetail entity)
		{
			this.SendPropertyChanging();
			entity.TheQuestion = this;
		}
		
		private void detach_ResultDetails(ResultDetail entity)
		{
			this.SendPropertyChanging();
			entity.TheQuestion = null;
		}
		
		private void attach_TestDetails(TestDetail entity)
		{
			this.SendPropertyChanging();
			entity.TheQuestion = this;
		}
		
		private void detach_TestDetails(TestDetail entity)
		{
			this.SendPropertyChanging();
			entity.TheQuestion = null;
		}
	}
}
#pragma warning restore 1591
