<?xml version="1.0" encoding="utf-8"?><Database Name="ExaminationManagement" Class="ExaminationManagementDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-P36EI8CN\SNAKE;Initial Catalog=ExaminationManagement;Integrated Security=True" SettingsObjectName="ExaminationManagement.Properties.Settings" SettingsPropertyName="ExaminationManagementConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Account" Member="Accounts">
    <Type Name="Account">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="Char(100) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Permission" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RegistryDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Account_ExamineeListDetail" Member="ExamineeListDetails" ThisKey="UserID" OtherKey="UserID" Type="ExamineeListDetail" />
      <Association Name="Account_Result" Member="Results" ThisKey="UserID" OtherKey="UserID" Type="Result" />
      <Association Name="AccountDetail_Account" Member="AccountDetail" ThisKey="UserID" OtherKey="UserID" Type="AccountDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TheTest" Member="TheTests">
    <Type Name="TheTest">
      <Column Name="TestID" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TestName" Type="System.String" DbType="Char(20) NOT NULL" CanBeNull="false" />
      <Association Name="TheTest_Result" Member="Results" ThisKey="TestID" OtherKey="TestID" Type="Result" />
      <Association Name="TheTest_TestDetail" Member="TestDetails" ThisKey="TestID" OtherKey="TestID" Type="TestDetail" />
      <Association Name="TheTest_TestListDetail" Member="TestListDetails" ThisKey="TestID" OtherKey="TestID" Type="TestListDetail" />
    </Type>
  </Table>
  <Table Name="dbo.AccountDetails" Member="AccountDetails">
    <Type Name="AccountDetail">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="PhoneNumber" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="Char(100) NOT NULL" CanBeNull="false" />
      <Column Name="DOB" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ClassID" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="GradeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AccountType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="temp" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="AccountDetail_Account" Member="Account" ThisKey="UserID" OtherKey="UserID" Type="Account" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.ExamineeList" Member="ExamineeLists">
    <Type Name="ExamineeList">
      <Column Name="ExamineeListID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ExamineeListName" Type="System.String" DbType="Char(20) NOT NULL" CanBeNull="false" />
      <Association Name="ExamineeList_ExamineeListDetail" Member="ExamineeListDetails" ThisKey="ExamineeListID" OtherKey="ExamineeListID" Type="ExamineeListDetail" />
      <Association Name="ExamineeList_TheExamination" Member="TheExaminations" ThisKey="ExamineeListID" OtherKey="ExamineeListID" Type="TheExamination" />
    </Type>
  </Table>
  <Table Name="dbo.ExamineeListDetails" Member="ExamineeListDetails">
    <Type Name="ExamineeListDetail">
      <Column Name="ExamineeListID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Account_ExamineeListDetail" Member="Account" ThisKey="UserID" OtherKey="UserID" Type="Account" IsForeignKey="true" />
      <Association Name="ExamineeList_ExamineeListDetail" Member="ExamineeList" ThisKey="ExamineeListID" OtherKey="ExamineeListID" Type="ExamineeList" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Result" Member="Results">
    <Type Name="Result">
      <Column Name="ResultID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TestID" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="TotalScore" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Times" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsSubmitted" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ExaminationID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Result_ResultDetail" Member="ResultDetails" ThisKey="ResultID" OtherKey="ResultID" Type="ResultDetail" />
      <Association Name="Account_Result" Member="Account" ThisKey="UserID" OtherKey="UserID" Type="Account" IsForeignKey="true" />
      <Association Name="TheTest_Result" Member="TheTest" ThisKey="TestID" OtherKey="TestID" Type="TheTest" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ResultDetails" Member="ResultDetails">
    <Type Name="ResultDetail">
      <Column Name="ResultDetailsID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="QuestionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ResultID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Answer" Type="System.String" DbType="Char(20) NOT NULL" CanBeNull="false" />
      <Column Name="Score" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Result_ResultDetail" Member="Result" ThisKey="ResultID" OtherKey="ResultID" Type="Result" IsForeignKey="true" />
      <Association Name="TheQuestion_ResultDetail" Member="TheQuestion" ThisKey="QuestionID" OtherKey="QuestionID" Type="TheQuestion" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TestDetails" Member="TestDetails">
    <Type Name="TestDetail">
      <Column Name="TestID" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="QuestionID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="TheTest_TestDetail" Member="TheTest" ThisKey="TestID" OtherKey="TestID" Type="TheTest" IsForeignKey="true" />
      <Association Name="TheQuestion_TestDetail" Member="TheQuestion" ThisKey="QuestionID" OtherKey="QuestionID" Type="TheQuestion" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TestList" Member="TestLists">
    <Type Name="TestList">
      <Column Name="TestListID" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TestListName" Type="System.String" DbType="Char(20) NOT NULL" CanBeNull="false" />
      <Association Name="TestList_TestListDetail" Member="TestListDetails" ThisKey="TestListID" OtherKey="TestListID" Type="TestListDetail" />
      <Association Name="TestList_TheExamination" Member="TheExaminations" ThisKey="TestListID" OtherKey="TestListID" Type="TheExamination" />
    </Type>
  </Table>
  <Table Name="dbo.TestListDetails" Member="TestListDetails">
    <Type Name="TestListDetail">
      <Column Name="TestListID" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TestID" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="TestList_TestListDetail" Member="TestList" ThisKey="TestListID" OtherKey="TestListID" Type="TestList" IsForeignKey="true" />
      <Association Name="TheTest_TestListDetail" Member="TheTest" ThisKey="TestID" OtherKey="TestID" Type="TheTest" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TheExamination" Member="TheExaminations">
    <Type Name="TheExamination">
      <Column Name="ExaminationID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TestListID" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="ExamineeListID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExaminationName" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ExaminationType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GradeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Time" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Creator" Type="System.String" DbType="Char(30) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="ExamineeList_TheExamination" Member="ExamineeList" ThisKey="ExamineeListID" OtherKey="ExamineeListID" Type="ExamineeList" IsForeignKey="true" />
      <Association Name="TestList_TheExamination" Member="TestList" ThisKey="TestListID" OtherKey="TestListID" Type="TestList" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TheQuestion" Member="TheQuestions">
    <Type Name="TheQuestion">
      <Column Name="QuestionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="QuestionLevel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="QuestionType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="QuestionContent" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ChoiceA" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ChoiceB" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ChoiceC" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ChoiceD" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ChoiceE" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ChoiceF" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Answer" Type="System.String" DbType="Char(20) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TheQuestion_ResultDetail" Member="ResultDetails" ThisKey="QuestionID" OtherKey="QuestionID" Type="ResultDetail" />
      <Association Name="TheQuestion_TestDetail" Member="TestDetails" ThisKey="QuestionID" OtherKey="QuestionID" Type="TestDetail" />
    </Type>
  </Table>
</Database>