#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExaminationManagement.Functions.ConnectDatabase
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ExaminationManagement")]
	public partial class ExaminationManagementDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAccount(Account instance);
    partial void UpdateAccount(Account instance);
    partial void DeleteAccount(Account instance);
    partial void InsertTheTest(TheTest instance);
    partial void UpdateTheTest(TheTest instance);
    partial void DeleteTheTest(TheTest instance);
    partial void InsertAccountDetail(AccountDetail instance);
    partial void UpdateAccountDetail(AccountDetail instance);
    partial void DeleteAccountDetail(AccountDetail instance);
    partial void InsertExamineeList(ExamineeList instance);
    partial void UpdateExamineeList(ExamineeList instance);
    partial void DeleteExamineeList(ExamineeList instance);
    partial void InsertQuestionList(QuestionList instance);
    partial void UpdateQuestionList(QuestionList instance);
    partial void DeleteQuestionList(QuestionList instance);
    partial void InsertResult(Result instance);
    partial void UpdateResult(Result instance);
    partial void DeleteResult(Result instance);
    partial void InsertTheExamination(TheExamination instance);
    partial void UpdateTheExamination(TheExamination instance);
    partial void DeleteTheExamination(TheExamination instance);
    partial void InsertTheQuestion(TheQuestion instance);
    partial void UpdateTheQuestion(TheQuestion instance);
    partial void DeleteTheQuestion(TheQuestion instance);
    #endregion
		
		public ExaminationManagementDataContext() : 
				base(global::ExaminationManagement.Properties.Settings.Default.ExaminationManagementConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public ExaminationManagementDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ExaminationManagementDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ExaminationManagementDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ExaminationManagementDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Account> Accounts
		{
			get
			{
				return this.GetTable<Account>();
			}
		}
		
		public System.Data.Linq.Table<TheTest> TheTests
		{
			get
			{
				return this.GetTable<TheTest>();
			}
		}
		
		public System.Data.Linq.Table<AccountDetail> AccountDetails
		{
			get
			{
				return this.GetTable<AccountDetail>();
			}
		}
		
		public System.Data.Linq.Table<ExamineeList> ExamineeLists
		{
			get
			{
				return this.GetTable<ExamineeList>();
			}
		}
		
		public System.Data.Linq.Table<QuestionList> QuestionLists
		{
			get
			{
				return this.GetTable<QuestionList>();
			}
		}
		
		public System.Data.Linq.Table<Result> Results
		{
			get
			{
				return this.GetTable<Result>();
			}
		}
		
		public System.Data.Linq.Table<TheExamination> TheExaminations
		{
			get
			{
				return this.GetTable<TheExamination>();
			}
		}
		
		public System.Data.Linq.Table<TheQuestion> TheQuestions
		{
			get
			{
				return this.GetTable<TheQuestion>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Account")]
	public partial class Account : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AccountID;
		
		private System.Nullable<int> _UserID;
		
		private string _Username;
		
		private string _Password;
		
		private int _Permission;
		
		private System.DateTime _RegistryDate;
		
		private EntitySet<ExamineeList> _ExamineeLists;
		
		private EntitySet<Result> _Results;
		
		private EntityRef<AccountDetail> _AccountDetail;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAccountIDChanging(int value);
    partial void OnAccountIDChanged();
    partial void OnUserIDChanging(System.Nullable<int> value);
    partial void OnUserIDChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnPermissionChanging(int value);
    partial void OnPermissionChanged();
    partial void OnRegistryDateChanging(System.DateTime value);
    partial void OnRegistryDateChanged();
    #endregion
		
		public Account()
		{
			this._ExamineeLists = new EntitySet<ExamineeList>(new Action<ExamineeList>(this.attach_ExamineeLists), new Action<ExamineeList>(this.detach_ExamineeLists));
			this._Results = new EntitySet<Result>(new Action<Result>(this.attach_Results), new Action<Result>(this.detach_Results));
			this._AccountDetail = default(EntityRef<AccountDetail>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int AccountID
		{
			get
			{
				return this._AccountID;
			}
			set
			{
				if ((this._AccountID != value))
				{
					this.OnAccountIDChanging(value);
					this.SendPropertyChanging();
					this._AccountID = value;
					this.SendPropertyChanged("AccountID");
					this.OnAccountIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int")]
		public System.Nullable<int> UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					if (this._AccountDetail.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="Char(100) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Permission", DbType="Int NOT NULL")]
		public int Permission
		{
			get
			{
				return this._Permission;
			}
			set
			{
				if ((this._Permission != value))
				{
					this.OnPermissionChanging(value);
					this.SendPropertyChanging();
					this._Permission = value;
					this.SendPropertyChanged("Permission");
					this.OnPermissionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegistryDate", DbType="DateTime NOT NULL")]
		public System.DateTime RegistryDate
		{
			get
			{
				return this._RegistryDate;
			}
			set
			{
				if ((this._RegistryDate != value))
				{
					this.OnRegistryDateChanging(value);
					this.SendPropertyChanging();
					this._RegistryDate = value;
					this.SendPropertyChanged("RegistryDate");
					this.OnRegistryDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Account_ExamineeList", Storage="_ExamineeLists", ThisKey="AccountID", OtherKey="AccountID")]
		public EntitySet<ExamineeList> ExamineeLists
		{
			get
			{
				return this._ExamineeLists;
			}
			set
			{
				this._ExamineeLists.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Account_Result", Storage="_Results", ThisKey="AccountID", OtherKey="AccountID")]
		public EntitySet<Result> Results
		{
			get
			{
				return this._Results;
			}
			set
			{
				this._Results.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AccountDetail_Account", Storage="_AccountDetail", ThisKey="UserID", OtherKey="UserID", IsForeignKey=true)]
		public AccountDetail AccountDetail
		{
			get
			{
				return this._AccountDetail.Entity;
			}
			set
			{
				AccountDetail previousValue = this._AccountDetail.Entity;
				if (((previousValue != value) 
							|| (this._AccountDetail.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._AccountDetail.Entity = null;
						previousValue.Accounts.Remove(this);
					}
					this._AccountDetail.Entity = value;
					if ((value != null))
					{
						value.Accounts.Add(this);
						this._UserID = value.UserID;
					}
					else
					{
						this._UserID = default(Nullable<int>);
					}
					this.SendPropertyChanged("AccountDetail");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ExamineeLists(ExamineeList entity)
		{
			this.SendPropertyChanging();
			entity.Account = this;
		}
		
		private void detach_ExamineeLists(ExamineeList entity)
		{
			this.SendPropertyChanging();
			entity.Account = null;
		}
		
		private void attach_Results(Result entity)
		{
			this.SendPropertyChanging();
			entity.Account = this;
		}
		
		private void detach_Results(Result entity)
		{
			this.SendPropertyChanging();
			entity.Account = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TheTest")]
	public partial class TheTest : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TestID;
		
		private int _QuestionListID;
		
		private EntitySet<Result> _Results;
		
		private EntitySet<TheExamination> _TheExaminations;
		
		private EntityRef<QuestionList> _QuestionList;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTestIDChanging(int value);
    partial void OnTestIDChanged();
    partial void OnQuestionListIDChanging(int value);
    partial void OnQuestionListIDChanged();
    #endregion
		
		public TheTest()
		{
			this._Results = new EntitySet<Result>(new Action<Result>(this.attach_Results), new Action<Result>(this.detach_Results));
			this._TheExaminations = new EntitySet<TheExamination>(new Action<TheExamination>(this.attach_TheExaminations), new Action<TheExamination>(this.detach_TheExaminations));
			this._QuestionList = default(EntityRef<QuestionList>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TestID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int TestID
		{
			get
			{
				return this._TestID;
			}
			set
			{
				if ((this._TestID != value))
				{
					this.OnTestIDChanging(value);
					this.SendPropertyChanging();
					this._TestID = value;
					this.SendPropertyChanged("TestID");
					this.OnTestIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuestionListID", DbType="Int NOT NULL")]
		public int QuestionListID
		{
			get
			{
				return this._QuestionListID;
			}
			set
			{
				if ((this._QuestionListID != value))
				{
					if (this._QuestionList.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnQuestionListIDChanging(value);
					this.SendPropertyChanging();
					this._QuestionListID = value;
					this.SendPropertyChanged("QuestionListID");
					this.OnQuestionListIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TheTest_Result", Storage="_Results", ThisKey="TestID", OtherKey="TestID")]
		public EntitySet<Result> Results
		{
			get
			{
				return this._Results;
			}
			set
			{
				this._Results.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TheTest_TheExamination", Storage="_TheExaminations", ThisKey="TestID", OtherKey="TestID")]
		public EntitySet<TheExamination> TheExaminations
		{
			get
			{
				return this._TheExaminations;
			}
			set
			{
				this._TheExaminations.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QuestionList_TheTest", Storage="_QuestionList", ThisKey="QuestionListID", OtherKey="QuestionListID", IsForeignKey=true)]
		public QuestionList QuestionList
		{
			get
			{
				return this._QuestionList.Entity;
			}
			set
			{
				QuestionList previousValue = this._QuestionList.Entity;
				if (((previousValue != value) 
							|| (this._QuestionList.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QuestionList.Entity = null;
						previousValue.TheTests.Remove(this);
					}
					this._QuestionList.Entity = value;
					if ((value != null))
					{
						value.TheTests.Add(this);
						this._QuestionListID = value.QuestionListID;
					}
					else
					{
						this._QuestionListID = default(int);
					}
					this.SendPropertyChanged("QuestionList");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Results(Result entity)
		{
			this.SendPropertyChanging();
			entity.TheTest = this;
		}
		
		private void detach_Results(Result entity)
		{
			this.SendPropertyChanging();
			entity.TheTest = null;
		}
		
		private void attach_TheExaminations(TheExamination entity)
		{
			this.SendPropertyChanging();
			entity.TheTest = this;
		}
		
		private void detach_TheExaminations(TheExamination entity)
		{
			this.SendPropertyChanging();
			entity.TheTest = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AccountDetails")]
	public partial class AccountDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UserID;
		
		private string _Name;
		
		private string _PhoneNumber;
		
		private string _Email;
		
		private System.DateTime _DOB;
		
		private string _Address;
		
		private string _ClassID;
		
		private int _GradeID;
		
		private int _AccountType;
		
		private string _temp;
		
		private EntitySet<Account> _Accounts;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIDChanging(int value);
    partial void OnUserIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnPhoneNumberChanging(string value);
    partial void OnPhoneNumberChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnDOBChanging(System.DateTime value);
    partial void OnDOBChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnClassIDChanging(string value);
    partial void OnClassIDChanged();
    partial void OnGradeIDChanging(int value);
    partial void OnGradeIDChanged();
    partial void OnAccountTypeChanging(int value);
    partial void OnAccountTypeChanged();
    partial void OntempChanging(string value);
    partial void OntempChanged();
    #endregion
		
		public AccountDetail()
		{
			this._Accounts = new EntitySet<Account>(new Action<Account>(this.attach_Accounts), new Action<Account>(this.detach_Accounts));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber", DbType="Char(10)")]
		public string PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				if ((this._PhoneNumber != value))
				{
					this.OnPhoneNumberChanging(value);
					this.SendPropertyChanging();
					this._PhoneNumber = value;
					this.SendPropertyChanged("PhoneNumber");
					this.OnPhoneNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="Char(100) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="DateTime NOT NULL")]
		public System.DateTime DOB
		{
			get
			{
				return this._DOB;
			}
			set
			{
				if ((this._DOB != value))
				{
					this.OnDOBChanging(value);
					this.SendPropertyChanging();
					this._DOB = value;
					this.SendPropertyChanged("DOB");
					this.OnDOBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(250)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClassID", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string ClassID
		{
			get
			{
				return this._ClassID;
			}
			set
			{
				if ((this._ClassID != value))
				{
					this.OnClassIDChanging(value);
					this.SendPropertyChanging();
					this._ClassID = value;
					this.SendPropertyChanged("ClassID");
					this.OnClassIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeID", DbType="Int NOT NULL")]
		public int GradeID
		{
			get
			{
				return this._GradeID;
			}
			set
			{
				if ((this._GradeID != value))
				{
					this.OnGradeIDChanging(value);
					this.SendPropertyChanging();
					this._GradeID = value;
					this.SendPropertyChanged("GradeID");
					this.OnGradeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountType", DbType="Int NOT NULL")]
		public int AccountType
		{
			get
			{
				return this._AccountType;
			}
			set
			{
				if ((this._AccountType != value))
				{
					this.OnAccountTypeChanging(value);
					this.SendPropertyChanging();
					this._AccountType = value;
					this.SendPropertyChanged("AccountType");
					this.OnAccountTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_temp", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string temp
		{
			get
			{
				return this._temp;
			}
			set
			{
				if ((this._temp != value))
				{
					this.OntempChanging(value);
					this.SendPropertyChanging();
					this._temp = value;
					this.SendPropertyChanged("temp");
					this.OntempChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AccountDetail_Account", Storage="_Accounts", ThisKey="UserID", OtherKey="UserID")]
		public EntitySet<Account> Accounts
		{
			get
			{
				return this._Accounts;
			}
			set
			{
				this._Accounts.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Accounts(Account entity)
		{
			this.SendPropertyChanging();
			entity.AccountDetail = this;
		}
		
		private void detach_Accounts(Account entity)
		{
			this.SendPropertyChanging();
			entity.AccountDetail = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ExamineeList")]
	public partial class ExamineeList : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ExamineeListID;
		
		private int _AccountID;
		
		private EntitySet<TheExamination> _TheExaminations;
		
		private EntityRef<Account> _Account;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnExamineeListIDChanging(int value);
    partial void OnExamineeListIDChanged();
    partial void OnAccountIDChanging(int value);
    partial void OnAccountIDChanged();
    #endregion
		
		public ExamineeList()
		{
			this._TheExaminations = new EntitySet<TheExamination>(new Action<TheExamination>(this.attach_TheExaminations), new Action<TheExamination>(this.detach_TheExaminations));
			this._Account = default(EntityRef<Account>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExamineeListID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ExamineeListID
		{
			get
			{
				return this._ExamineeListID;
			}
			set
			{
				if ((this._ExamineeListID != value))
				{
					this.OnExamineeListIDChanging(value);
					this.SendPropertyChanging();
					this._ExamineeListID = value;
					this.SendPropertyChanged("ExamineeListID");
					this.OnExamineeListIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountID", DbType="Int NOT NULL")]
		public int AccountID
		{
			get
			{
				return this._AccountID;
			}
			set
			{
				if ((this._AccountID != value))
				{
					if (this._Account.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAccountIDChanging(value);
					this.SendPropertyChanging();
					this._AccountID = value;
					this.SendPropertyChanged("AccountID");
					this.OnAccountIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ExamineeList_TheExamination", Storage="_TheExaminations", ThisKey="ExamineeListID", OtherKey="ExamineeListID")]
		public EntitySet<TheExamination> TheExaminations
		{
			get
			{
				return this._TheExaminations;
			}
			set
			{
				this._TheExaminations.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Account_ExamineeList", Storage="_Account", ThisKey="AccountID", OtherKey="AccountID", IsForeignKey=true)]
		public Account Account
		{
			get
			{
				return this._Account.Entity;
			}
			set
			{
				Account previousValue = this._Account.Entity;
				if (((previousValue != value) 
							|| (this._Account.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Account.Entity = null;
						previousValue.ExamineeLists.Remove(this);
					}
					this._Account.Entity = value;
					if ((value != null))
					{
						value.ExamineeLists.Add(this);
						this._AccountID = value.AccountID;
					}
					else
					{
						this._AccountID = default(int);
					}
					this.SendPropertyChanged("Account");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TheExaminations(TheExamination entity)
		{
			this.SendPropertyChanging();
			entity.ExamineeList = this;
		}
		
		private void detach_TheExaminations(TheExamination entity)
		{
			this.SendPropertyChanging();
			entity.ExamineeList = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QuestionList")]
	public partial class QuestionList : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _QuestionListID;
		
		private int _QuestionID;
		
		private string _QuestionListName;
		
		private EntitySet<TheTest> _TheTests;
		
		private EntityRef<TheQuestion> _TheQuestion;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnQuestionListIDChanging(int value);
    partial void OnQuestionListIDChanged();
    partial void OnQuestionIDChanging(int value);
    partial void OnQuestionIDChanged();
    partial void OnQuestionListNameChanging(string value);
    partial void OnQuestionListNameChanged();
    #endregion
		
		public QuestionList()
		{
			this._TheTests = new EntitySet<TheTest>(new Action<TheTest>(this.attach_TheTests), new Action<TheTest>(this.detach_TheTests));
			this._TheQuestion = default(EntityRef<TheQuestion>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuestionListID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int QuestionListID
		{
			get
			{
				return this._QuestionListID;
			}
			set
			{
				if ((this._QuestionListID != value))
				{
					this.OnQuestionListIDChanging(value);
					this.SendPropertyChanging();
					this._QuestionListID = value;
					this.SendPropertyChanged("QuestionListID");
					this.OnQuestionListIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuestionID", DbType="Int NOT NULL")]
		public int QuestionID
		{
			get
			{
				return this._QuestionID;
			}
			set
			{
				if ((this._QuestionID != value))
				{
					if (this._TheQuestion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnQuestionIDChanging(value);
					this.SendPropertyChanging();
					this._QuestionID = value;
					this.SendPropertyChanged("QuestionID");
					this.OnQuestionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuestionListName", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string QuestionListName
		{
			get
			{
				return this._QuestionListName;
			}
			set
			{
				if ((this._QuestionListName != value))
				{
					this.OnQuestionListNameChanging(value);
					this.SendPropertyChanging();
					this._QuestionListName = value;
					this.SendPropertyChanged("QuestionListName");
					this.OnQuestionListNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QuestionList_TheTest", Storage="_TheTests", ThisKey="QuestionListID", OtherKey="QuestionListID")]
		public EntitySet<TheTest> TheTests
		{
			get
			{
				return this._TheTests;
			}
			set
			{
				this._TheTests.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TheQuestion_QuestionList", Storage="_TheQuestion", ThisKey="QuestionID", OtherKey="QuestionID", IsForeignKey=true)]
		public TheQuestion TheQuestion
		{
			get
			{
				return this._TheQuestion.Entity;
			}
			set
			{
				TheQuestion previousValue = this._TheQuestion.Entity;
				if (((previousValue != value) 
							|| (this._TheQuestion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TheQuestion.Entity = null;
						previousValue.QuestionLists.Remove(this);
					}
					this._TheQuestion.Entity = value;
					if ((value != null))
					{
						value.QuestionLists.Add(this);
						this._QuestionID = value.QuestionID;
					}
					else
					{
						this._QuestionID = default(int);
					}
					this.SendPropertyChanged("TheQuestion");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TheTests(TheTest entity)
		{
			this.SendPropertyChanging();
			entity.QuestionList = this;
		}
		
		private void detach_TheTests(TheTest entity)
		{
			this.SendPropertyChanging();
			entity.QuestionList = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Result")]
	public partial class Result : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ResultID;
		
		private int _AccountID;
		
		private int _TestID;
		
		private int _Score;
		
		private EntityRef<Account> _Account;
		
		private EntityRef<TheTest> _TheTest;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnResultIDChanging(int value);
    partial void OnResultIDChanged();
    partial void OnAccountIDChanging(int value);
    partial void OnAccountIDChanged();
    partial void OnTestIDChanging(int value);
    partial void OnTestIDChanged();
    partial void OnScoreChanging(int value);
    partial void OnScoreChanged();
    #endregion
		
		public Result()
		{
			this._Account = default(EntityRef<Account>);
			this._TheTest = default(EntityRef<TheTest>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResultID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ResultID
		{
			get
			{
				return this._ResultID;
			}
			set
			{
				if ((this._ResultID != value))
				{
					this.OnResultIDChanging(value);
					this.SendPropertyChanging();
					this._ResultID = value;
					this.SendPropertyChanged("ResultID");
					this.OnResultIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountID", DbType="Int NOT NULL")]
		public int AccountID
		{
			get
			{
				return this._AccountID;
			}
			set
			{
				if ((this._AccountID != value))
				{
					if (this._Account.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAccountIDChanging(value);
					this.SendPropertyChanging();
					this._AccountID = value;
					this.SendPropertyChanged("AccountID");
					this.OnAccountIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TestID", DbType="Int NOT NULL")]
		public int TestID
		{
			get
			{
				return this._TestID;
			}
			set
			{
				if ((this._TestID != value))
				{
					if (this._TheTest.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTestIDChanging(value);
					this.SendPropertyChanging();
					this._TestID = value;
					this.SendPropertyChanged("TestID");
					this.OnTestIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Score", DbType="Int NOT NULL")]
		public int Score
		{
			get
			{
				return this._Score;
			}
			set
			{
				if ((this._Score != value))
				{
					this.OnScoreChanging(value);
					this.SendPropertyChanging();
					this._Score = value;
					this.SendPropertyChanged("Score");
					this.OnScoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Account_Result", Storage="_Account", ThisKey="AccountID", OtherKey="AccountID", IsForeignKey=true)]
		public Account Account
		{
			get
			{
				return this._Account.Entity;
			}
			set
			{
				Account previousValue = this._Account.Entity;
				if (((previousValue != value) 
							|| (this._Account.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Account.Entity = null;
						previousValue.Results.Remove(this);
					}
					this._Account.Entity = value;
					if ((value != null))
					{
						value.Results.Add(this);
						this._AccountID = value.AccountID;
					}
					else
					{
						this._AccountID = default(int);
					}
					this.SendPropertyChanged("Account");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TheTest_Result", Storage="_TheTest", ThisKey="TestID", OtherKey="TestID", IsForeignKey=true)]
		public TheTest TheTest
		{
			get
			{
				return this._TheTest.Entity;
			}
			set
			{
				TheTest previousValue = this._TheTest.Entity;
				if (((previousValue != value) 
							|| (this._TheTest.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TheTest.Entity = null;
						previousValue.Results.Remove(this);
					}
					this._TheTest.Entity = value;
					if ((value != null))
					{
						value.Results.Add(this);
						this._TestID = value.TestID;
					}
					else
					{
						this._TestID = default(int);
					}
					this.SendPropertyChanged("TheTest");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TheExamination")]
	public partial class TheExamination : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ExaminationID;
		
		private System.Nullable<int> _TestID;
		
		private System.Nullable<int> _ExamineeListID;
		
		private string _ExaminationName;
		
		private int _ExaminationType;
		
		private int _GradeID;
		
		private string _Creator;
		
		private System.DateTime _CreateDate;
		
		private System.Nullable<System.DateTime> _StartDate;
		
		private System.Nullable<System.DateTime> _EndDate;
		
		private EntityRef<ExamineeList> _ExamineeList;
		
		private EntityRef<TheTest> _TheTest;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnExaminationIDChanging(int value);
    partial void OnExaminationIDChanged();
    partial void OnTestIDChanging(System.Nullable<int> value);
    partial void OnTestIDChanged();
    partial void OnExamineeListIDChanging(System.Nullable<int> value);
    partial void OnExamineeListIDChanged();
    partial void OnExaminationNameChanging(string value);
    partial void OnExaminationNameChanged();
    partial void OnExaminationTypeChanging(int value);
    partial void OnExaminationTypeChanged();
    partial void OnGradeIDChanging(int value);
    partial void OnGradeIDChanged();
    partial void OnCreatorChanging(string value);
    partial void OnCreatorChanged();
    partial void OnCreateDateChanging(System.DateTime value);
    partial void OnCreateDateChanged();
    partial void OnStartDateChanging(System.Nullable<System.DateTime> value);
    partial void OnStartDateChanged();
    partial void OnEndDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEndDateChanged();
    #endregion
		
		public TheExamination()
		{
			this._ExamineeList = default(EntityRef<ExamineeList>);
			this._TheTest = default(EntityRef<TheTest>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExaminationID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ExaminationID
		{
			get
			{
				return this._ExaminationID;
			}
			set
			{
				if ((this._ExaminationID != value))
				{
					this.OnExaminationIDChanging(value);
					this.SendPropertyChanging();
					this._ExaminationID = value;
					this.SendPropertyChanged("ExaminationID");
					this.OnExaminationIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TestID", DbType="Int")]
		public System.Nullable<int> TestID
		{
			get
			{
				return this._TestID;
			}
			set
			{
				if ((this._TestID != value))
				{
					if (this._TheTest.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTestIDChanging(value);
					this.SendPropertyChanging();
					this._TestID = value;
					this.SendPropertyChanged("TestID");
					this.OnTestIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExamineeListID", DbType="Int")]
		public System.Nullable<int> ExamineeListID
		{
			get
			{
				return this._ExamineeListID;
			}
			set
			{
				if ((this._ExamineeListID != value))
				{
					if (this._ExamineeList.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnExamineeListIDChanging(value);
					this.SendPropertyChanging();
					this._ExamineeListID = value;
					this.SendPropertyChanged("ExamineeListID");
					this.OnExamineeListIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExaminationName", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string ExaminationName
		{
			get
			{
				return this._ExaminationName;
			}
			set
			{
				if ((this._ExaminationName != value))
				{
					this.OnExaminationNameChanging(value);
					this.SendPropertyChanging();
					this._ExaminationName = value;
					this.SendPropertyChanged("ExaminationName");
					this.OnExaminationNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExaminationType", DbType="Int NOT NULL")]
		public int ExaminationType
		{
			get
			{
				return this._ExaminationType;
			}
			set
			{
				if ((this._ExaminationType != value))
				{
					this.OnExaminationTypeChanging(value);
					this.SendPropertyChanging();
					this._ExaminationType = value;
					this.SendPropertyChanged("ExaminationType");
					this.OnExaminationTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeID", DbType="Int NOT NULL")]
		public int GradeID
		{
			get
			{
				return this._GradeID;
			}
			set
			{
				if ((this._GradeID != value))
				{
					this.OnGradeIDChanging(value);
					this.SendPropertyChanging();
					this._GradeID = value;
					this.SendPropertyChanged("GradeID");
					this.OnGradeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Creator", DbType="Char(30) NOT NULL", CanBeNull=false)]
		public string Creator
		{
			get
			{
				return this._Creator;
			}
			set
			{
				if ((this._Creator != value))
				{
					this.OnCreatorChanging(value);
					this.SendPropertyChanging();
					this._Creator = value;
					this.SendPropertyChanged("Creator");
					this.OnCreatorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime NOT NULL")]
		public System.DateTime CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> StartDate
		{
			get
			{
				return this._StartDate;
			}
			set
			{
				if ((this._StartDate != value))
				{
					this.OnStartDateChanging(value);
					this.SendPropertyChanging();
					this._StartDate = value;
					this.SendPropertyChanged("StartDate");
					this.OnStartDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EndDate
		{
			get
			{
				return this._EndDate;
			}
			set
			{
				if ((this._EndDate != value))
				{
					this.OnEndDateChanging(value);
					this.SendPropertyChanging();
					this._EndDate = value;
					this.SendPropertyChanged("EndDate");
					this.OnEndDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ExamineeList_TheExamination", Storage="_ExamineeList", ThisKey="ExamineeListID", OtherKey="ExamineeListID", IsForeignKey=true)]
		public ExamineeList ExamineeList
		{
			get
			{
				return this._ExamineeList.Entity;
			}
			set
			{
				ExamineeList previousValue = this._ExamineeList.Entity;
				if (((previousValue != value) 
							|| (this._ExamineeList.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ExamineeList.Entity = null;
						previousValue.TheExaminations.Remove(this);
					}
					this._ExamineeList.Entity = value;
					if ((value != null))
					{
						value.TheExaminations.Add(this);
						this._ExamineeListID = value.ExamineeListID;
					}
					else
					{
						this._ExamineeListID = default(Nullable<int>);
					}
					this.SendPropertyChanged("ExamineeList");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TheTest_TheExamination", Storage="_TheTest", ThisKey="TestID", OtherKey="TestID", IsForeignKey=true)]
		public TheTest TheTest
		{
			get
			{
				return this._TheTest.Entity;
			}
			set
			{
				TheTest previousValue = this._TheTest.Entity;
				if (((previousValue != value) 
							|| (this._TheTest.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TheTest.Entity = null;
						previousValue.TheExaminations.Remove(this);
					}
					this._TheTest.Entity = value;
					if ((value != null))
					{
						value.TheExaminations.Add(this);
						this._TestID = value.TestID;
					}
					else
					{
						this._TestID = default(Nullable<int>);
					}
					this.SendPropertyChanged("TheTest");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TheQuestion")]
	public partial class TheQuestion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _QuestionID;
		
		private int _QuestionLevel;
		
		private int _QuestionType;
		
		private string _QuestionContent;
		
		private string _ChoiceA;
		
		private string _ChoiceB;
		
		private string _ChoiceC;
		
		private string _ChoiceD;
		
		private string _ChoiceE;
		
		private string _ChoiceF;
		
		private string _Answer;
		
		private System.Nullable<int> _UserID;
		
		private EntitySet<QuestionList> _QuestionLists;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnQuestionIDChanging(int value);
    partial void OnQuestionIDChanged();
    partial void OnQuestionLevelChanging(int value);
    partial void OnQuestionLevelChanged();
    partial void OnQuestionTypeChanging(int value);
    partial void OnQuestionTypeChanged();
    partial void OnQuestionContentChanging(string value);
    partial void OnQuestionContentChanged();
    partial void OnChoiceAChanging(string value);
    partial void OnChoiceAChanged();
    partial void OnChoiceBChanging(string value);
    partial void OnChoiceBChanged();
    partial void OnChoiceCChanging(string value);
    partial void OnChoiceCChanged();
    partial void OnChoiceDChanging(string value);
    partial void OnChoiceDChanged();
    partial void OnChoiceEChanging(string value);
    partial void OnChoiceEChanged();
    partial void OnChoiceFChanging(string value);
    partial void OnChoiceFChanged();
    partial void OnAnswerChanging(string value);
    partial void OnAnswerChanged();
    partial void OnUserIDChanging(System.Nullable<int> value);
    partial void OnUserIDChanged();
    #endregion
		
		public TheQuestion()
		{
			this._QuestionLists = new EntitySet<QuestionList>(new Action<QuestionList>(this.attach_QuestionLists), new Action<QuestionList>(this.detach_QuestionLists));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuestionID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int QuestionID
		{
			get
			{
				return this._QuestionID;
			}
			set
			{
				if ((this._QuestionID != value))
				{
					this.OnQuestionIDChanging(value);
					this.SendPropertyChanging();
					this._QuestionID = value;
					this.SendPropertyChanged("QuestionID");
					this.OnQuestionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuestionLevel", DbType="Int NOT NULL")]
		public int QuestionLevel
		{
			get
			{
				return this._QuestionLevel;
			}
			set
			{
				if ((this._QuestionLevel != value))
				{
					this.OnQuestionLevelChanging(value);
					this.SendPropertyChanging();
					this._QuestionLevel = value;
					this.SendPropertyChanged("QuestionLevel");
					this.OnQuestionLevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuestionType", DbType="Int NOT NULL")]
		public int QuestionType
		{
			get
			{
				return this._QuestionType;
			}
			set
			{
				if ((this._QuestionType != value))
				{
					this.OnQuestionTypeChanging(value);
					this.SendPropertyChanging();
					this._QuestionType = value;
					this.SendPropertyChanged("QuestionType");
					this.OnQuestionTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuestionContent", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string QuestionContent
		{
			get
			{
				return this._QuestionContent;
			}
			set
			{
				if ((this._QuestionContent != value))
				{
					this.OnQuestionContentChanging(value);
					this.SendPropertyChanging();
					this._QuestionContent = value;
					this.SendPropertyChanged("QuestionContent");
					this.OnQuestionContentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChoiceA", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string ChoiceA
		{
			get
			{
				return this._ChoiceA;
			}
			set
			{
				if ((this._ChoiceA != value))
				{
					this.OnChoiceAChanging(value);
					this.SendPropertyChanging();
					this._ChoiceA = value;
					this.SendPropertyChanged("ChoiceA");
					this.OnChoiceAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChoiceB", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string ChoiceB
		{
			get
			{
				return this._ChoiceB;
			}
			set
			{
				if ((this._ChoiceB != value))
				{
					this.OnChoiceBChanging(value);
					this.SendPropertyChanging();
					this._ChoiceB = value;
					this.SendPropertyChanged("ChoiceB");
					this.OnChoiceBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChoiceC", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string ChoiceC
		{
			get
			{
				return this._ChoiceC;
			}
			set
			{
				if ((this._ChoiceC != value))
				{
					this.OnChoiceCChanging(value);
					this.SendPropertyChanging();
					this._ChoiceC = value;
					this.SendPropertyChanged("ChoiceC");
					this.OnChoiceCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChoiceD", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string ChoiceD
		{
			get
			{
				return this._ChoiceD;
			}
			set
			{
				if ((this._ChoiceD != value))
				{
					this.OnChoiceDChanging(value);
					this.SendPropertyChanging();
					this._ChoiceD = value;
					this.SendPropertyChanged("ChoiceD");
					this.OnChoiceDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChoiceE", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string ChoiceE
		{
			get
			{
				return this._ChoiceE;
			}
			set
			{
				if ((this._ChoiceE != value))
				{
					this.OnChoiceEChanging(value);
					this.SendPropertyChanging();
					this._ChoiceE = value;
					this.SendPropertyChanged("ChoiceE");
					this.OnChoiceEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChoiceF", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string ChoiceF
		{
			get
			{
				return this._ChoiceF;
			}
			set
			{
				if ((this._ChoiceF != value))
				{
					this.OnChoiceFChanging(value);
					this.SendPropertyChanging();
					this._ChoiceF = value;
					this.SendPropertyChanged("ChoiceF");
					this.OnChoiceFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Answer", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Answer
		{
			get
			{
				return this._Answer;
			}
			set
			{
				if ((this._Answer != value))
				{
					this.OnAnswerChanging(value);
					this.SendPropertyChanging();
					this._Answer = value;
					this.SendPropertyChanged("Answer");
					this.OnAnswerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int")]
		public System.Nullable<int> UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TheQuestion_QuestionList", Storage="_QuestionLists", ThisKey="QuestionID", OtherKey="QuestionID")]
		public EntitySet<QuestionList> QuestionLists
		{
			get
			{
				return this._QuestionLists;
			}
			set
			{
				this._QuestionLists.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_QuestionLists(QuestionList entity)
		{
			this.SendPropertyChanging();
			entity.TheQuestion = this;
		}
		
		private void detach_QuestionLists(QuestionList entity)
		{
			this.SendPropertyChanging();
			entity.TheQuestion = null;
		}
	}
}
#pragma warning restore 1591
