#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExaminationManagement
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ExaminationManagement")]
	public partial class ExaminationManagementDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTheTest(TheTest instance);
    partial void UpdateTheTest(TheTest instance);
    partial void DeleteTheTest(TheTest instance);
    partial void InsertAccount(Account instance);
    partial void UpdateAccount(Account instance);
    partial void DeleteAccount(Account instance);
    partial void InsertExamineeList(ExamineeList instance);
    partial void UpdateExamineeList(ExamineeList instance);
    partial void DeleteExamineeList(ExamineeList instance);
    partial void InsertQuestionList(QuestionList instance);
    partial void UpdateQuestionList(QuestionList instance);
    partial void DeleteQuestionList(QuestionList instance);
    partial void InsertStudent(Student instance);
    partial void UpdateStudent(Student instance);
    partial void DeleteStudent(Student instance);
    partial void InsertTeacher(Teacher instance);
    partial void UpdateTeacher(Teacher instance);
    partial void DeleteTeacher(Teacher instance);
    partial void InsertTheExamination(TheExamination instance);
    partial void UpdateTheExamination(TheExamination instance);
    partial void DeleteTheExamination(TheExamination instance);
    partial void InsertTheQuestion(TheQuestion instance);
    partial void UpdateTheQuestion(TheQuestion instance);
    partial void DeleteTheQuestion(TheQuestion instance);
    partial void InsertTheResult(TheResult instance);
    partial void UpdateTheResult(TheResult instance);
    partial void DeleteTheResult(TheResult instance);
    #endregion
		
		public ExaminationManagementDataContext() : 
				base(global::ExaminationManagement.Properties.Settings.Default.ExaminationManagementConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ExaminationManagementDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ExaminationManagementDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ExaminationManagementDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ExaminationManagementDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TheTest> TheTests
		{
			get
			{
				return this.GetTable<TheTest>();
			}
		}
		
		public System.Data.Linq.Table<Account> Accounts
		{
			get
			{
				return this.GetTable<Account>();
			}
		}
		
		public System.Data.Linq.Table<ExamineeList> ExamineeLists
		{
			get
			{
				return this.GetTable<ExamineeList>();
			}
		}
		
		public System.Data.Linq.Table<QuestionList> QuestionLists
		{
			get
			{
				return this.GetTable<QuestionList>();
			}
		}
		
		public System.Data.Linq.Table<Student> Students
		{
			get
			{
				return this.GetTable<Student>();
			}
		}
		
		public System.Data.Linq.Table<Teacher> Teachers
		{
			get
			{
				return this.GetTable<Teacher>();
			}
		}
		
		public System.Data.Linq.Table<TheExamination> TheExaminations
		{
			get
			{
				return this.GetTable<TheExamination>();
			}
		}
		
		public System.Data.Linq.Table<TheQuestion> TheQuestions
		{
			get
			{
				return this.GetTable<TheQuestion>();
			}
		}
		
		public System.Data.Linq.Table<TheResult> TheResults
		{
			get
			{
				return this.GetTable<TheResult>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TheTest")]
	public partial class TheTest : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _testID;
		
		private string _listID;
		
		private EntitySet<TheExamination> _TheExaminations;
		
		private EntitySet<TheResult> _TheResults;
		
		private EntityRef<QuestionList> _QuestionList;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OntestIDChanging(string value);
    partial void OntestIDChanged();
    partial void OnlistIDChanging(string value);
    partial void OnlistIDChanged();
    #endregion
		
		public TheTest()
		{
			this._TheExaminations = new EntitySet<TheExamination>(new Action<TheExamination>(this.attach_TheExaminations), new Action<TheExamination>(this.detach_TheExaminations));
			this._TheResults = new EntitySet<TheResult>(new Action<TheResult>(this.attach_TheResults), new Action<TheResult>(this.detach_TheResults));
			this._QuestionList = default(EntityRef<QuestionList>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_testID", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string testID
		{
			get
			{
				return this._testID;
			}
			set
			{
				if ((this._testID != value))
				{
					this.OntestIDChanging(value);
					this.SendPropertyChanging();
					this._testID = value;
					this.SendPropertyChanged("testID");
					this.OntestIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_listID", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string listID
		{
			get
			{
				return this._listID;
			}
			set
			{
				if ((this._listID != value))
				{
					if (this._QuestionList.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnlistIDChanging(value);
					this.SendPropertyChanging();
					this._listID = value;
					this.SendPropertyChanged("listID");
					this.OnlistIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TheTest_TheExamination", Storage="_TheExaminations", ThisKey="testID", OtherKey="testID")]
		public EntitySet<TheExamination> TheExaminations
		{
			get
			{
				return this._TheExaminations;
			}
			set
			{
				this._TheExaminations.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TheTest_TheResult", Storage="_TheResults", ThisKey="testID", OtherKey="testID")]
		public EntitySet<TheResult> TheResults
		{
			get
			{
				return this._TheResults;
			}
			set
			{
				this._TheResults.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QuestionList_TheTest", Storage="_QuestionList", ThisKey="listID", OtherKey="listID", IsForeignKey=true)]
		public QuestionList QuestionList
		{
			get
			{
				return this._QuestionList.Entity;
			}
			set
			{
				QuestionList previousValue = this._QuestionList.Entity;
				if (((previousValue != value) 
							|| (this._QuestionList.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QuestionList.Entity = null;
						previousValue.TheTests.Remove(this);
					}
					this._QuestionList.Entity = value;
					if ((value != null))
					{
						value.TheTests.Add(this);
						this._listID = value.listID;
					}
					else
					{
						this._listID = default(string);
					}
					this.SendPropertyChanged("QuestionList");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TheExaminations(TheExamination entity)
		{
			this.SendPropertyChanging();
			entity.TheTest = this;
		}
		
		private void detach_TheExaminations(TheExamination entity)
		{
			this.SendPropertyChanging();
			entity.TheTest = null;
		}
		
		private void attach_TheResults(TheResult entity)
		{
			this.SendPropertyChanging();
			entity.TheTest = this;
		}
		
		private void detach_TheResults(TheResult entity)
		{
			this.SendPropertyChanging();
			entity.TheTest = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Account")]
	public partial class Account : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _userID;
		
		private string _permission;
		
		private string _username;
		
		private string _password;
		
		private System.DateTime _reg_date;
		
		private EntitySet<ExamineeList> _ExamineeLists;
		
		private EntitySet<TheResult> _TheResults;
		
		private EntityRef<Student> _Student;
		
		private EntityRef<Teacher> _Teacher;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuserIDChanging(string value);
    partial void OnuserIDChanged();
    partial void OnpermissionChanging(string value);
    partial void OnpermissionChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void Onreg_dateChanging(System.DateTime value);
    partial void Onreg_dateChanged();
    #endregion
		
		public Account()
		{
			this._ExamineeLists = new EntitySet<ExamineeList>(new Action<ExamineeList>(this.attach_ExamineeLists), new Action<ExamineeList>(this.detach_ExamineeLists));
			this._TheResults = new EntitySet<TheResult>(new Action<TheResult>(this.attach_TheResults), new Action<TheResult>(this.detach_TheResults));
			this._Student = default(EntityRef<Student>);
			this._Teacher = default(EntityRef<Teacher>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userID", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string userID
		{
			get
			{
				return this._userID;
			}
			set
			{
				if ((this._userID != value))
				{
					if ((this._Student.HasLoadedOrAssignedValue || this._Teacher.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnuserIDChanging(value);
					this.SendPropertyChanging();
					this._userID = value;
					this.SendPropertyChanged("userID");
					this.OnuserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_permission", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string permission
		{
			get
			{
				return this._permission;
			}
			set
			{
				if ((this._permission != value))
				{
					this.OnpermissionChanging(value);
					this.SendPropertyChanging();
					this._permission = value;
					this.SendPropertyChanged("permission");
					this.OnpermissionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reg_date", DbType="DateTime NOT NULL")]
		public System.DateTime reg_date
		{
			get
			{
				return this._reg_date;
			}
			set
			{
				if ((this._reg_date != value))
				{
					this.Onreg_dateChanging(value);
					this.SendPropertyChanging();
					this._reg_date = value;
					this.SendPropertyChanged("reg_date");
					this.Onreg_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Account_ExamineeList", Storage="_ExamineeLists", ThisKey="userID", OtherKey="userID")]
		public EntitySet<ExamineeList> ExamineeLists
		{
			get
			{
				return this._ExamineeLists;
			}
			set
			{
				this._ExamineeLists.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Account_TheResult", Storage="_TheResults", ThisKey="userID", OtherKey="testID")]
		public EntitySet<TheResult> TheResults
		{
			get
			{
				return this._TheResults;
			}
			set
			{
				this._TheResults.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Student_Account", Storage="_Student", ThisKey="userID", OtherKey="userID", IsForeignKey=true)]
		public Student Student
		{
			get
			{
				return this._Student.Entity;
			}
			set
			{
				Student previousValue = this._Student.Entity;
				if (((previousValue != value) 
							|| (this._Student.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Student.Entity = null;
						previousValue.Account = null;
					}
					this._Student.Entity = value;
					if ((value != null))
					{
						value.Account = this;
						this._userID = value.userID;
					}
					else
					{
						this._userID = default(string);
					}
					this.SendPropertyChanged("Student");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Teacher_Account", Storage="_Teacher", ThisKey="userID", OtherKey="userID", IsForeignKey=true)]
		public Teacher Teacher
		{
			get
			{
				return this._Teacher.Entity;
			}
			set
			{
				Teacher previousValue = this._Teacher.Entity;
				if (((previousValue != value) 
							|| (this._Teacher.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Teacher.Entity = null;
						previousValue.Account = null;
					}
					this._Teacher.Entity = value;
					if ((value != null))
					{
						value.Account = this;
						this._userID = value.userID;
					}
					else
					{
						this._userID = default(string);
					}
					this.SendPropertyChanged("Teacher");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ExamineeLists(ExamineeList entity)
		{
			this.SendPropertyChanging();
			entity.Account = this;
		}
		
		private void detach_ExamineeLists(ExamineeList entity)
		{
			this.SendPropertyChanging();
			entity.Account = null;
		}
		
		private void attach_TheResults(TheResult entity)
		{
			this.SendPropertyChanging();
			entity.Account = this;
		}
		
		private void detach_TheResults(TheResult entity)
		{
			this.SendPropertyChanging();
			entity.Account = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ExamineeList")]
	public partial class ExamineeList : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _exListID;
		
		private string _userID;
		
		private string _exam_type;
		
		private EntityRef<Account> _Account;
		
		private EntityRef<TheExamination> _TheExamination;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnexListIDChanging(string value);
    partial void OnexListIDChanged();
    partial void OnuserIDChanging(string value);
    partial void OnuserIDChanged();
    partial void Onexam_typeChanging(string value);
    partial void Onexam_typeChanged();
    #endregion
		
		public ExamineeList()
		{
			this._Account = default(EntityRef<Account>);
			this._TheExamination = default(EntityRef<TheExamination>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exListID", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string exListID
		{
			get
			{
				return this._exListID;
			}
			set
			{
				if ((this._exListID != value))
				{
					if (this._TheExamination.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnexListIDChanging(value);
					this.SendPropertyChanging();
					this._exListID = value;
					this.SendPropertyChanged("exListID");
					this.OnexListIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userID", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string userID
		{
			get
			{
				return this._userID;
			}
			set
			{
				if ((this._userID != value))
				{
					if (this._Account.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnuserIDChanging(value);
					this.SendPropertyChanging();
					this._userID = value;
					this.SendPropertyChanged("userID");
					this.OnuserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exam_type", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string exam_type
		{
			get
			{
				return this._exam_type;
			}
			set
			{
				if ((this._exam_type != value))
				{
					this.Onexam_typeChanging(value);
					this.SendPropertyChanging();
					this._exam_type = value;
					this.SendPropertyChanged("exam_type");
					this.Onexam_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Account_ExamineeList", Storage="_Account", ThisKey="userID", OtherKey="userID", IsForeignKey=true)]
		public Account Account
		{
			get
			{
				return this._Account.Entity;
			}
			set
			{
				Account previousValue = this._Account.Entity;
				if (((previousValue != value) 
							|| (this._Account.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Account.Entity = null;
						previousValue.ExamineeLists.Remove(this);
					}
					this._Account.Entity = value;
					if ((value != null))
					{
						value.ExamineeLists.Add(this);
						this._userID = value.userID;
					}
					else
					{
						this._userID = default(string);
					}
					this.SendPropertyChanged("Account");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TheExamination_ExamineeList", Storage="_TheExamination", ThisKey="exListID", OtherKey="examID", IsForeignKey=true)]
		public TheExamination TheExamination
		{
			get
			{
				return this._TheExamination.Entity;
			}
			set
			{
				TheExamination previousValue = this._TheExamination.Entity;
				if (((previousValue != value) 
							|| (this._TheExamination.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TheExamination.Entity = null;
						previousValue.ExamineeLists.Remove(this);
					}
					this._TheExamination.Entity = value;
					if ((value != null))
					{
						value.ExamineeLists.Add(this);
						this._exListID = value.examID;
					}
					else
					{
						this._exListID = default(string);
					}
					this.SendPropertyChanged("TheExamination");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QuestionList")]
	public partial class QuestionList : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _listID;
		
		private int _questionID;
		
		private EntitySet<TheTest> _TheTests;
		
		private EntityRef<TheQuestion> _TheQuestion;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnlistIDChanging(string value);
    partial void OnlistIDChanged();
    partial void OnquestionIDChanging(int value);
    partial void OnquestionIDChanged();
    #endregion
		
		public QuestionList()
		{
			this._TheTests = new EntitySet<TheTest>(new Action<TheTest>(this.attach_TheTests), new Action<TheTest>(this.detach_TheTests));
			this._TheQuestion = default(EntityRef<TheQuestion>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_listID", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string listID
		{
			get
			{
				return this._listID;
			}
			set
			{
				if ((this._listID != value))
				{
					this.OnlistIDChanging(value);
					this.SendPropertyChanging();
					this._listID = value;
					this.SendPropertyChanged("listID");
					this.OnlistIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_questionID", DbType="Int NOT NULL")]
		public int questionID
		{
			get
			{
				return this._questionID;
			}
			set
			{
				if ((this._questionID != value))
				{
					if (this._TheQuestion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnquestionIDChanging(value);
					this.SendPropertyChanging();
					this._questionID = value;
					this.SendPropertyChanged("questionID");
					this.OnquestionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QuestionList_TheTest", Storage="_TheTests", ThisKey="listID", OtherKey="listID")]
		public EntitySet<TheTest> TheTests
		{
			get
			{
				return this._TheTests;
			}
			set
			{
				this._TheTests.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TheQuestion_QuestionList", Storage="_TheQuestion", ThisKey="questionID", OtherKey="questionID", IsForeignKey=true)]
		public TheQuestion TheQuestion
		{
			get
			{
				return this._TheQuestion.Entity;
			}
			set
			{
				TheQuestion previousValue = this._TheQuestion.Entity;
				if (((previousValue != value) 
							|| (this._TheQuestion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TheQuestion.Entity = null;
						previousValue.QuestionLists.Remove(this);
					}
					this._TheQuestion.Entity = value;
					if ((value != null))
					{
						value.QuestionLists.Add(this);
						this._questionID = value.questionID;
					}
					else
					{
						this._questionID = default(int);
					}
					this.SendPropertyChanged("TheQuestion");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TheTests(TheTest entity)
		{
			this.SendPropertyChanging();
			entity.QuestionList = this;
		}
		
		private void detach_TheTests(TheTest entity)
		{
			this.SendPropertyChanging();
			entity.QuestionList = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Student")]
	public partial class Student : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _name;
		
		private string _userID;
		
		private System.DateTime _dob;
		
		private string _classID;
		
		private EntityRef<Account> _Account;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnuserIDChanging(string value);
    partial void OnuserIDChanged();
    partial void OndobChanging(System.DateTime value);
    partial void OndobChanged();
    partial void OnclassIDChanging(string value);
    partial void OnclassIDChanged();
    #endregion
		
		public Student()
		{
			this._Account = default(EntityRef<Account>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userID", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string userID
		{
			get
			{
				return this._userID;
			}
			set
			{
				if ((this._userID != value))
				{
					this.OnuserIDChanging(value);
					this.SendPropertyChanging();
					this._userID = value;
					this.SendPropertyChanged("userID");
					this.OnuserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dob", DbType="DateTime NOT NULL")]
		public System.DateTime dob
		{
			get
			{
				return this._dob;
			}
			set
			{
				if ((this._dob != value))
				{
					this.OndobChanging(value);
					this.SendPropertyChanging();
					this._dob = value;
					this.SendPropertyChanged("dob");
					this.OndobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_classID", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string classID
		{
			get
			{
				return this._classID;
			}
			set
			{
				if ((this._classID != value))
				{
					this.OnclassIDChanging(value);
					this.SendPropertyChanging();
					this._classID = value;
					this.SendPropertyChanged("classID");
					this.OnclassIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Student_Account", Storage="_Account", ThisKey="userID", OtherKey="userID", IsUnique=true, IsForeignKey=false)]
		public Account Account
		{
			get
			{
				return this._Account.Entity;
			}
			set
			{
				Account previousValue = this._Account.Entity;
				if (((previousValue != value) 
							|| (this._Account.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Account.Entity = null;
						previousValue.Student = null;
					}
					this._Account.Entity = value;
					if ((value != null))
					{
						value.Student = this;
					}
					this.SendPropertyChanged("Account");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Teacher")]
	public partial class Teacher : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _userID;
		
		private string _name;
		
		private System.DateTime _dob;
		
		private EntityRef<Account> _Account;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuserIDChanging(string value);
    partial void OnuserIDChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OndobChanging(System.DateTime value);
    partial void OndobChanged();
    #endregion
		
		public Teacher()
		{
			this._Account = default(EntityRef<Account>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userID", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string userID
		{
			get
			{
				return this._userID;
			}
			set
			{
				if ((this._userID != value))
				{
					this.OnuserIDChanging(value);
					this.SendPropertyChanging();
					this._userID = value;
					this.SendPropertyChanged("userID");
					this.OnuserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dob", DbType="DateTime NOT NULL")]
		public System.DateTime dob
		{
			get
			{
				return this._dob;
			}
			set
			{
				if ((this._dob != value))
				{
					this.OndobChanging(value);
					this.SendPropertyChanging();
					this._dob = value;
					this.SendPropertyChanged("dob");
					this.OndobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Teacher_Account", Storage="_Account", ThisKey="userID", OtherKey="userID", IsUnique=true, IsForeignKey=false)]
		public Account Account
		{
			get
			{
				return this._Account.Entity;
			}
			set
			{
				Account previousValue = this._Account.Entity;
				if (((previousValue != value) 
							|| (this._Account.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Account.Entity = null;
						previousValue.Teacher = null;
					}
					this._Account.Entity = value;
					if ((value != null))
					{
						value.Teacher = this;
					}
					this.SendPropertyChanged("Account");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TheExamination")]
	public partial class TheExamination : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _examID;
		
		private string _testID;
		
		private string _exam_type;
		
		private System.DateTime _date_time;
		
		private string _name;
		
		private string _exListID;
		
		private EntitySet<ExamineeList> _ExamineeLists;
		
		private EntityRef<TheTest> _TheTest;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnexamIDChanging(string value);
    partial void OnexamIDChanged();
    partial void OntestIDChanging(string value);
    partial void OntestIDChanged();
    partial void Onexam_typeChanging(string value);
    partial void Onexam_typeChanged();
    partial void Ondate_timeChanging(System.DateTime value);
    partial void Ondate_timeChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnexListIDChanging(string value);
    partial void OnexListIDChanged();
    #endregion
		
		public TheExamination()
		{
			this._ExamineeLists = new EntitySet<ExamineeList>(new Action<ExamineeList>(this.attach_ExamineeLists), new Action<ExamineeList>(this.detach_ExamineeLists));
			this._TheTest = default(EntityRef<TheTest>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_examID", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string examID
		{
			get
			{
				return this._examID;
			}
			set
			{
				if ((this._examID != value))
				{
					this.OnexamIDChanging(value);
					this.SendPropertyChanging();
					this._examID = value;
					this.SendPropertyChanged("examID");
					this.OnexamIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_testID", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string testID
		{
			get
			{
				return this._testID;
			}
			set
			{
				if ((this._testID != value))
				{
					if (this._TheTest.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OntestIDChanging(value);
					this.SendPropertyChanging();
					this._testID = value;
					this.SendPropertyChanged("testID");
					this.OntestIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exam_type", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string exam_type
		{
			get
			{
				return this._exam_type;
			}
			set
			{
				if ((this._exam_type != value))
				{
					this.Onexam_typeChanging(value);
					this.SendPropertyChanging();
					this._exam_type = value;
					this.SendPropertyChanged("exam_type");
					this.Onexam_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_time", DbType="DateTime NOT NULL")]
		public System.DateTime date_time
		{
			get
			{
				return this._date_time;
			}
			set
			{
				if ((this._date_time != value))
				{
					this.Ondate_timeChanging(value);
					this.SendPropertyChanging();
					this._date_time = value;
					this.SendPropertyChanged("date_time");
					this.Ondate_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exListID", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string exListID
		{
			get
			{
				return this._exListID;
			}
			set
			{
				if ((this._exListID != value))
				{
					this.OnexListIDChanging(value);
					this.SendPropertyChanging();
					this._exListID = value;
					this.SendPropertyChanged("exListID");
					this.OnexListIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TheExamination_ExamineeList", Storage="_ExamineeLists", ThisKey="examID", OtherKey="exListID")]
		public EntitySet<ExamineeList> ExamineeLists
		{
			get
			{
				return this._ExamineeLists;
			}
			set
			{
				this._ExamineeLists.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TheTest_TheExamination", Storage="_TheTest", ThisKey="testID", OtherKey="testID", IsForeignKey=true)]
		public TheTest TheTest
		{
			get
			{
				return this._TheTest.Entity;
			}
			set
			{
				TheTest previousValue = this._TheTest.Entity;
				if (((previousValue != value) 
							|| (this._TheTest.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TheTest.Entity = null;
						previousValue.TheExaminations.Remove(this);
					}
					this._TheTest.Entity = value;
					if ((value != null))
					{
						value.TheExaminations.Add(this);
						this._testID = value.testID;
					}
					else
					{
						this._testID = default(string);
					}
					this.SendPropertyChanged("TheTest");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ExamineeLists(ExamineeList entity)
		{
			this.SendPropertyChanging();
			entity.TheExamination = this;
		}
		
		private void detach_ExamineeLists(ExamineeList entity)
		{
			this.SendPropertyChanging();
			entity.TheExamination = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TheQuestion")]
	public partial class TheQuestion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _questionID;
		
		private string _level;
		
		private string _content;
		
		private string _choiceA;
		
		private string _choiceB;
		
		private string _choiceC;
		
		private string _choiceD;
		
		private string _choiceE;
		
		private string _choiceF;
		
		private string _answer;
		
		private EntitySet<QuestionList> _QuestionLists;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnquestionIDChanging(int value);
    partial void OnquestionIDChanged();
    partial void OnlevelChanging(string value);
    partial void OnlevelChanged();
    partial void OncontentChanging(string value);
    partial void OncontentChanged();
    partial void OnchoiceAChanging(string value);
    partial void OnchoiceAChanged();
    partial void OnchoiceBChanging(string value);
    partial void OnchoiceBChanged();
    partial void OnchoiceCChanging(string value);
    partial void OnchoiceCChanged();
    partial void OnchoiceDChanging(string value);
    partial void OnchoiceDChanged();
    partial void OnchoiceEChanging(string value);
    partial void OnchoiceEChanged();
    partial void OnchoiceFChanging(string value);
    partial void OnchoiceFChanged();
    partial void OnanswerChanging(string value);
    partial void OnanswerChanged();
    #endregion
		
		public TheQuestion()
		{
			this._QuestionLists = new EntitySet<QuestionList>(new Action<QuestionList>(this.attach_QuestionLists), new Action<QuestionList>(this.detach_QuestionLists));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_questionID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int questionID
		{
			get
			{
				return this._questionID;
			}
			set
			{
				if ((this._questionID != value))
				{
					this.OnquestionIDChanging(value);
					this.SendPropertyChanging();
					this._questionID = value;
					this.SendPropertyChanged("questionID");
					this.OnquestionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[level]", Storage="_level", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string level
		{
			get
			{
				return this._level;
			}
			set
			{
				if ((this._level != value))
				{
					this.OnlevelChanging(value);
					this.SendPropertyChanging();
					this._level = value;
					this.SendPropertyChanged("level");
					this.OnlevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_content", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string content
		{
			get
			{
				return this._content;
			}
			set
			{
				if ((this._content != value))
				{
					this.OncontentChanging(value);
					this.SendPropertyChanging();
					this._content = value;
					this.SendPropertyChanged("content");
					this.OncontentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_choiceA", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string choiceA
		{
			get
			{
				return this._choiceA;
			}
			set
			{
				if ((this._choiceA != value))
				{
					this.OnchoiceAChanging(value);
					this.SendPropertyChanging();
					this._choiceA = value;
					this.SendPropertyChanged("choiceA");
					this.OnchoiceAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_choiceB", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string choiceB
		{
			get
			{
				return this._choiceB;
			}
			set
			{
				if ((this._choiceB != value))
				{
					this.OnchoiceBChanging(value);
					this.SendPropertyChanging();
					this._choiceB = value;
					this.SendPropertyChanged("choiceB");
					this.OnchoiceBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_choiceC", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string choiceC
		{
			get
			{
				return this._choiceC;
			}
			set
			{
				if ((this._choiceC != value))
				{
					this.OnchoiceCChanging(value);
					this.SendPropertyChanging();
					this._choiceC = value;
					this.SendPropertyChanged("choiceC");
					this.OnchoiceCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_choiceD", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string choiceD
		{
			get
			{
				return this._choiceD;
			}
			set
			{
				if ((this._choiceD != value))
				{
					this.OnchoiceDChanging(value);
					this.SendPropertyChanging();
					this._choiceD = value;
					this.SendPropertyChanged("choiceD");
					this.OnchoiceDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_choiceE", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string choiceE
		{
			get
			{
				return this._choiceE;
			}
			set
			{
				if ((this._choiceE != value))
				{
					this.OnchoiceEChanging(value);
					this.SendPropertyChanging();
					this._choiceE = value;
					this.SendPropertyChanged("choiceE");
					this.OnchoiceEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_choiceF", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string choiceF
		{
			get
			{
				return this._choiceF;
			}
			set
			{
				if ((this._choiceF != value))
				{
					this.OnchoiceFChanging(value);
					this.SendPropertyChanging();
					this._choiceF = value;
					this.SendPropertyChanged("choiceF");
					this.OnchoiceFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_answer", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string answer
		{
			get
			{
				return this._answer;
			}
			set
			{
				if ((this._answer != value))
				{
					this.OnanswerChanging(value);
					this.SendPropertyChanging();
					this._answer = value;
					this.SendPropertyChanged("answer");
					this.OnanswerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TheQuestion_QuestionList", Storage="_QuestionLists", ThisKey="questionID", OtherKey="questionID")]
		public EntitySet<QuestionList> QuestionLists
		{
			get
			{
				return this._QuestionLists;
			}
			set
			{
				this._QuestionLists.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_QuestionLists(QuestionList entity)
		{
			this.SendPropertyChanging();
			entity.TheQuestion = this;
		}
		
		private void detach_QuestionLists(QuestionList entity)
		{
			this.SendPropertyChanging();
			entity.TheQuestion = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TheResult")]
	public partial class TheResult : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _testID;
		
		private string _userID;
		
		private int _the_score;
		
		private EntityRef<Account> _Account;
		
		private EntityRef<TheTest> _TheTest;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OntestIDChanging(string value);
    partial void OntestIDChanged();
    partial void OnuserIDChanging(string value);
    partial void OnuserIDChanged();
    partial void Onthe_scoreChanging(int value);
    partial void Onthe_scoreChanged();
    #endregion
		
		public TheResult()
		{
			this._Account = default(EntityRef<Account>);
			this._TheTest = default(EntityRef<TheTest>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_testID", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string testID
		{
			get
			{
				return this._testID;
			}
			set
			{
				if ((this._testID != value))
				{
					if ((this._Account.HasLoadedOrAssignedValue || this._TheTest.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OntestIDChanging(value);
					this.SendPropertyChanging();
					this._testID = value;
					this.SendPropertyChanged("testID");
					this.OntestIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userID", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string userID
		{
			get
			{
				return this._userID;
			}
			set
			{
				if ((this._userID != value))
				{
					this.OnuserIDChanging(value);
					this.SendPropertyChanging();
					this._userID = value;
					this.SendPropertyChanged("userID");
					this.OnuserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_the_score", DbType="Int NOT NULL")]
		public int the_score
		{
			get
			{
				return this._the_score;
			}
			set
			{
				if ((this._the_score != value))
				{
					this.Onthe_scoreChanging(value);
					this.SendPropertyChanging();
					this._the_score = value;
					this.SendPropertyChanged("the_score");
					this.Onthe_scoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Account_TheResult", Storage="_Account", ThisKey="testID", OtherKey="userID", IsForeignKey=true)]
		public Account Account
		{
			get
			{
				return this._Account.Entity;
			}
			set
			{
				Account previousValue = this._Account.Entity;
				if (((previousValue != value) 
							|| (this._Account.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Account.Entity = null;
						previousValue.TheResults.Remove(this);
					}
					this._Account.Entity = value;
					if ((value != null))
					{
						value.TheResults.Add(this);
						this._testID = value.userID;
					}
					else
					{
						this._testID = default(string);
					}
					this.SendPropertyChanged("Account");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TheTest_TheResult", Storage="_TheTest", ThisKey="testID", OtherKey="testID", IsForeignKey=true)]
		public TheTest TheTest
		{
			get
			{
				return this._TheTest.Entity;
			}
			set
			{
				TheTest previousValue = this._TheTest.Entity;
				if (((previousValue != value) 
							|| (this._TheTest.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TheTest.Entity = null;
						previousValue.TheResults.Remove(this);
					}
					this._TheTest.Entity = value;
					if ((value != null))
					{
						value.TheResults.Add(this);
						this._testID = value.testID;
					}
					else
					{
						this._testID = default(string);
					}
					this.SendPropertyChanged("TheTest");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
