#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExaminationManagement
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ExaminationManagement")]
	public partial class ExaminationManagementDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAccount(Account instance);
    partial void UpdateAccount(Account instance);
    partial void DeleteAccount(Account instance);
    partial void InsertExamineeList(ExamineeList instance);
    partial void UpdateExamineeList(ExamineeList instance);
    partial void DeleteExamineeList(ExamineeList instance);
    partial void InsertQuestionList(QuestionList instance);
    partial void UpdateQuestionList(QuestionList instance);
    partial void DeleteQuestionList(QuestionList instance);
    partial void InsertStudent(Student instance);
    partial void UpdateStudent(Student instance);
    partial void DeleteStudent(Student instance);
    partial void InsertStudentDetail(StudentDetail instance);
    partial void UpdateStudentDetail(StudentDetail instance);
    partial void DeleteStudentDetail(StudentDetail instance);
    partial void InsertTeacher(Teacher instance);
    partial void UpdateTeacher(Teacher instance);
    partial void DeleteTeacher(Teacher instance);
    partial void InsertTeacherDetail(TeacherDetail instance);
    partial void UpdateTeacherDetail(TeacherDetail instance);
    partial void DeleteTeacherDetail(TeacherDetail instance);
    partial void InsertTheExamination(TheExamination instance);
    partial void UpdateTheExamination(TheExamination instance);
    partial void DeleteTheExamination(TheExamination instance);
    partial void InsertTheQuestion(TheQuestion instance);
    partial void UpdateTheQuestion(TheQuestion instance);
    partial void DeleteTheQuestion(TheQuestion instance);
    partial void InsertTheResult(TheResult instance);
    partial void UpdateTheResult(TheResult instance);
    partial void DeleteTheResult(TheResult instance);
    partial void InsertTheTest(TheTest instance);
    partial void UpdateTheTest(TheTest instance);
    partial void DeleteTheTest(TheTest instance);
    #endregion
		
		public ExaminationManagementDataContext() : 
				base(global::ExaminationManagement.Properties.Settings.Default.ExaminationManagementConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ExaminationManagementDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ExaminationManagementDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ExaminationManagementDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ExaminationManagementDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Account> Accounts
		{
			get
			{
				return this.GetTable<Account>();
			}
		}
		
		public System.Data.Linq.Table<ExamineeList> ExamineeLists
		{
			get
			{
				return this.GetTable<ExamineeList>();
			}
		}
		
		public System.Data.Linq.Table<QuestionList> QuestionLists
		{
			get
			{
				return this.GetTable<QuestionList>();
			}
		}
		
		public System.Data.Linq.Table<Student> Students
		{
			get
			{
				return this.GetTable<Student>();
			}
		}
		
		public System.Data.Linq.Table<StudentDetail> StudentDetails
		{
			get
			{
				return this.GetTable<StudentDetail>();
			}
		}
		
		public System.Data.Linq.Table<Teacher> Teachers
		{
			get
			{
				return this.GetTable<Teacher>();
			}
		}
		
		public System.Data.Linq.Table<TeacherDetail> TeacherDetails
		{
			get
			{
				return this.GetTable<TeacherDetail>();
			}
		}
		
		public System.Data.Linq.Table<TheExamination> TheExaminations
		{
			get
			{
				return this.GetTable<TheExamination>();
			}
		}
		
		public System.Data.Linq.Table<TheQuestion> TheQuestions
		{
			get
			{
				return this.GetTable<TheQuestion>();
			}
		}
		
		public System.Data.Linq.Table<TheResult> TheResults
		{
			get
			{
				return this.GetTable<TheResult>();
			}
		}
		
		public System.Data.Linq.Table<TheTest> TheTests
		{
			get
			{
				return this.GetTable<TheTest>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Account")]
	public partial class Account : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _UserID;
		
		private string _Username;
		
		private string _Password;
		
		private string _Permission;
		
		private System.Nullable<System.DateTime> _RegistryDate;
		
		private EntitySet<ExamineeList> _ExamineeLists;
		
		private EntitySet<Student> _Students;
		
		private EntitySet<Teacher> _Teachers;
		
		private EntitySet<TheResult> _TheResults;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIDChanging(string value);
    partial void OnUserIDChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnPermissionChanging(string value);
    partial void OnPermissionChanged();
    partial void OnRegistryDateChanging(System.Nullable<System.DateTime> value);
    partial void OnRegistryDateChanged();
    #endregion
		
		public Account()
		{
			this._ExamineeLists = new EntitySet<ExamineeList>(new Action<ExamineeList>(this.attach_ExamineeLists), new Action<ExamineeList>(this.detach_ExamineeLists));
			this._Students = new EntitySet<Student>(new Action<Student>(this.attach_Students), new Action<Student>(this.detach_Students));
			this._Teachers = new EntitySet<Teacher>(new Action<Teacher>(this.attach_Teachers), new Action<Teacher>(this.detach_Teachers));
			this._TheResults = new EntitySet<TheResult>(new Action<TheResult>(this.attach_TheResults), new Action<TheResult>(this.detach_TheResults));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NChar(30) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Permission", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Permission
		{
			get
			{
				return this._Permission;
			}
			set
			{
				if ((this._Permission != value))
				{
					this.OnPermissionChanging(value);
					this.SendPropertyChanging();
					this._Permission = value;
					this.SendPropertyChanged("Permission");
					this.OnPermissionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegistryDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> RegistryDate
		{
			get
			{
				return this._RegistryDate;
			}
			set
			{
				if ((this._RegistryDate != value))
				{
					this.OnRegistryDateChanging(value);
					this.SendPropertyChanging();
					this._RegistryDate = value;
					this.SendPropertyChanged("RegistryDate");
					this.OnRegistryDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Account_ExamineeList", Storage="_ExamineeLists", ThisKey="UserID", OtherKey="UserID")]
		public EntitySet<ExamineeList> ExamineeLists
		{
			get
			{
				return this._ExamineeLists;
			}
			set
			{
				this._ExamineeLists.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Account_Student", Storage="_Students", ThisKey="UserID", OtherKey="UserID")]
		public EntitySet<Student> Students
		{
			get
			{
				return this._Students;
			}
			set
			{
				this._Students.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Account_Teacher", Storage="_Teachers", ThisKey="UserID", OtherKey="UserID")]
		public EntitySet<Teacher> Teachers
		{
			get
			{
				return this._Teachers;
			}
			set
			{
				this._Teachers.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Account_TheResult", Storage="_TheResults", ThisKey="UserID", OtherKey="TestID")]
		public EntitySet<TheResult> TheResults
		{
			get
			{
				return this._TheResults;
			}
			set
			{
				this._TheResults.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ExamineeLists(ExamineeList entity)
		{
			this.SendPropertyChanging();
			entity.Account = this;
		}
		
		private void detach_ExamineeLists(ExamineeList entity)
		{
			this.SendPropertyChanging();
			entity.Account = null;
		}
		
		private void attach_Students(Student entity)
		{
			this.SendPropertyChanging();
			entity.Account = this;
		}
		
		private void detach_Students(Student entity)
		{
			this.SendPropertyChanging();
			entity.Account = null;
		}
		
		private void attach_Teachers(Teacher entity)
		{
			this.SendPropertyChanging();
			entity.Account = this;
		}
		
		private void detach_Teachers(Teacher entity)
		{
			this.SendPropertyChanging();
			entity.Account = null;
		}
		
		private void attach_TheResults(TheResult entity)
		{
			this.SendPropertyChanging();
			entity.Account = this;
		}
		
		private void detach_TheResults(TheResult entity)
		{
			this.SendPropertyChanging();
			entity.Account = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ExamineeList")]
	public partial class ExamineeList : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ExamineeListID;
		
		private string _UserID;
		
		private string _ExaminationType;
		
		private EntityRef<Account> _Account;
		
		private EntityRef<TheExamination> _TheExamination;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnExamineeListIDChanging(string value);
    partial void OnExamineeListIDChanged();
    partial void OnUserIDChanging(string value);
    partial void OnUserIDChanged();
    partial void OnExaminationTypeChanging(string value);
    partial void OnExaminationTypeChanged();
    #endregion
		
		public ExamineeList()
		{
			this._Account = default(EntityRef<Account>);
			this._TheExamination = default(EntityRef<TheExamination>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExamineeListID", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ExamineeListID
		{
			get
			{
				return this._ExamineeListID;
			}
			set
			{
				if ((this._ExamineeListID != value))
				{
					if (this._TheExamination.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnExamineeListIDChanging(value);
					this.SendPropertyChanging();
					this._ExamineeListID = value;
					this.SendPropertyChanged("ExamineeListID");
					this.OnExamineeListIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					if (this._Account.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExaminationType", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string ExaminationType
		{
			get
			{
				return this._ExaminationType;
			}
			set
			{
				if ((this._ExaminationType != value))
				{
					this.OnExaminationTypeChanging(value);
					this.SendPropertyChanging();
					this._ExaminationType = value;
					this.SendPropertyChanged("ExaminationType");
					this.OnExaminationTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Account_ExamineeList", Storage="_Account", ThisKey="UserID", OtherKey="UserID", IsForeignKey=true)]
		public Account Account
		{
			get
			{
				return this._Account.Entity;
			}
			set
			{
				Account previousValue = this._Account.Entity;
				if (((previousValue != value) 
							|| (this._Account.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Account.Entity = null;
						previousValue.ExamineeLists.Remove(this);
					}
					this._Account.Entity = value;
					if ((value != null))
					{
						value.ExamineeLists.Add(this);
						this._UserID = value.UserID;
					}
					else
					{
						this._UserID = default(string);
					}
					this.SendPropertyChanged("Account");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TheExamination_ExamineeList", Storage="_TheExamination", ThisKey="ExamineeListID", OtherKey="ExamID", IsForeignKey=true)]
		public TheExamination TheExamination
		{
			get
			{
				return this._TheExamination.Entity;
			}
			set
			{
				TheExamination previousValue = this._TheExamination.Entity;
				if (((previousValue != value) 
							|| (this._TheExamination.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TheExamination.Entity = null;
						previousValue.ExamineeLists.Remove(this);
					}
					this._TheExamination.Entity = value;
					if ((value != null))
					{
						value.ExamineeLists.Add(this);
						this._ExamineeListID = value.ExamID;
					}
					else
					{
						this._ExamineeListID = default(string);
					}
					this.SendPropertyChanged("TheExamination");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QuestionList")]
	public partial class QuestionList : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ListID;
		
		private string _QuestionID;
		
		private EntitySet<TheTest> _TheTests;
		
		private EntityRef<TheQuestion> _TheQuestion;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnListIDChanging(string value);
    partial void OnListIDChanged();
    partial void OnQuestionIDChanging(string value);
    partial void OnQuestionIDChanged();
    #endregion
		
		public QuestionList()
		{
			this._TheTests = new EntitySet<TheTest>(new Action<TheTest>(this.attach_TheTests), new Action<TheTest>(this.detach_TheTests));
			this._TheQuestion = default(EntityRef<TheQuestion>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ListID", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ListID
		{
			get
			{
				return this._ListID;
			}
			set
			{
				if ((this._ListID != value))
				{
					this.OnListIDChanging(value);
					this.SendPropertyChanging();
					this._ListID = value;
					this.SendPropertyChanged("ListID");
					this.OnListIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuestionID", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string QuestionID
		{
			get
			{
				return this._QuestionID;
			}
			set
			{
				if ((this._QuestionID != value))
				{
					if (this._TheQuestion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnQuestionIDChanging(value);
					this.SendPropertyChanging();
					this._QuestionID = value;
					this.SendPropertyChanged("QuestionID");
					this.OnQuestionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QuestionList_TheTest", Storage="_TheTests", ThisKey="ListID", OtherKey="ListID")]
		public EntitySet<TheTest> TheTests
		{
			get
			{
				return this._TheTests;
			}
			set
			{
				this._TheTests.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TheQuestion_QuestionList", Storage="_TheQuestion", ThisKey="QuestionID", OtherKey="QuestionID", IsForeignKey=true)]
		public TheQuestion TheQuestion
		{
			get
			{
				return this._TheQuestion.Entity;
			}
			set
			{
				TheQuestion previousValue = this._TheQuestion.Entity;
				if (((previousValue != value) 
							|| (this._TheQuestion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TheQuestion.Entity = null;
						previousValue.QuestionLists.Remove(this);
					}
					this._TheQuestion.Entity = value;
					if ((value != null))
					{
						value.QuestionLists.Add(this);
						this._QuestionID = value.QuestionID;
					}
					else
					{
						this._QuestionID = default(string);
					}
					this.SendPropertyChanged("TheQuestion");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TheTests(TheTest entity)
		{
			this.SendPropertyChanging();
			entity.QuestionList = this;
		}
		
		private void detach_TheTests(TheTest entity)
		{
			this.SendPropertyChanging();
			entity.QuestionList = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Student")]
	public partial class Student : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _StudentID;
		
		private string _UserID;
		
		private EntityRef<Account> _Account;
		
		private EntityRef<StudentDetail> _StudentDetail;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStudentIDChanging(string value);
    partial void OnStudentIDChanged();
    partial void OnUserIDChanging(string value);
    partial void OnUserIDChanged();
    #endregion
		
		public Student()
		{
			this._Account = default(EntityRef<Account>);
			this._StudentDetail = default(EntityRef<StudentDetail>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentID", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string StudentID
		{
			get
			{
				return this._StudentID;
			}
			set
			{
				if ((this._StudentID != value))
				{
					if (this._StudentDetail.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnStudentIDChanging(value);
					this.SendPropertyChanging();
					this._StudentID = value;
					this.SendPropertyChanged("StudentID");
					this.OnStudentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					if (this._Account.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Account_Student", Storage="_Account", ThisKey="UserID", OtherKey="UserID", IsForeignKey=true)]
		public Account Account
		{
			get
			{
				return this._Account.Entity;
			}
			set
			{
				Account previousValue = this._Account.Entity;
				if (((previousValue != value) 
							|| (this._Account.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Account.Entity = null;
						previousValue.Students.Remove(this);
					}
					this._Account.Entity = value;
					if ((value != null))
					{
						value.Students.Add(this);
						this._UserID = value.UserID;
					}
					else
					{
						this._UserID = default(string);
					}
					this.SendPropertyChanged("Account");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="StudentDetail_Student", Storage="_StudentDetail", ThisKey="StudentID", OtherKey="StudentID", IsForeignKey=true)]
		public StudentDetail StudentDetail
		{
			get
			{
				return this._StudentDetail.Entity;
			}
			set
			{
				StudentDetail previousValue = this._StudentDetail.Entity;
				if (((previousValue != value) 
							|| (this._StudentDetail.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._StudentDetail.Entity = null;
						previousValue.Students.Remove(this);
					}
					this._StudentDetail.Entity = value;
					if ((value != null))
					{
						value.Students.Add(this);
						this._StudentID = value.StudentID;
					}
					else
					{
						this._StudentID = default(string);
					}
					this.SendPropertyChanged("StudentDetail");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StudentDetails")]
	public partial class StudentDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _StudentID;
		
		private string _StudentName;
		
		private System.DateTime _DOB;
		
		private string _ClassID;
		
		private string _GradeID;
		
		private EntitySet<Student> _Students;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStudentIDChanging(string value);
    partial void OnStudentIDChanged();
    partial void OnStudentNameChanging(string value);
    partial void OnStudentNameChanged();
    partial void OnDOBChanging(System.DateTime value);
    partial void OnDOBChanged();
    partial void OnClassIDChanging(string value);
    partial void OnClassIDChanged();
    partial void OnGradeIDChanging(string value);
    partial void OnGradeIDChanged();
    #endregion
		
		public StudentDetail()
		{
			this._Students = new EntitySet<Student>(new Action<Student>(this.attach_Students), new Action<Student>(this.detach_Students));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentID", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string StudentID
		{
			get
			{
				return this._StudentID;
			}
			set
			{
				if ((this._StudentID != value))
				{
					this.OnStudentIDChanging(value);
					this.SendPropertyChanging();
					this._StudentID = value;
					this.SendPropertyChanged("StudentID");
					this.OnStudentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentName", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string StudentName
		{
			get
			{
				return this._StudentName;
			}
			set
			{
				if ((this._StudentName != value))
				{
					this.OnStudentNameChanging(value);
					this.SendPropertyChanging();
					this._StudentName = value;
					this.SendPropertyChanged("StudentName");
					this.OnStudentNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="DateTime NOT NULL")]
		public System.DateTime DOB
		{
			get
			{
				return this._DOB;
			}
			set
			{
				if ((this._DOB != value))
				{
					this.OnDOBChanging(value);
					this.SendPropertyChanging();
					this._DOB = value;
					this.SendPropertyChanged("DOB");
					this.OnDOBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClassID", DbType="NChar(10)")]
		public string ClassID
		{
			get
			{
				return this._ClassID;
			}
			set
			{
				if ((this._ClassID != value))
				{
					this.OnClassIDChanging(value);
					this.SendPropertyChanging();
					this._ClassID = value;
					this.SendPropertyChanged("ClassID");
					this.OnClassIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeID", DbType="NChar(10)")]
		public string GradeID
		{
			get
			{
				return this._GradeID;
			}
			set
			{
				if ((this._GradeID != value))
				{
					this.OnGradeIDChanging(value);
					this.SendPropertyChanging();
					this._GradeID = value;
					this.SendPropertyChanged("GradeID");
					this.OnGradeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="StudentDetail_Student", Storage="_Students", ThisKey="StudentID", OtherKey="StudentID")]
		public EntitySet<Student> Students
		{
			get
			{
				return this._Students;
			}
			set
			{
				this._Students.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Students(Student entity)
		{
			this.SendPropertyChanging();
			entity.StudentDetail = this;
		}
		
		private void detach_Students(Student entity)
		{
			this.SendPropertyChanging();
			entity.StudentDetail = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Teacher")]
	public partial class Teacher : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TeacherID;
		
		private string _UserID;
		
		private EntityRef<Account> _Account;
		
		private EntityRef<TeacherDetail> _TeacherDetail;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTeacherIDChanging(string value);
    partial void OnTeacherIDChanged();
    partial void OnUserIDChanging(string value);
    partial void OnUserIDChanged();
    #endregion
		
		public Teacher()
		{
			this._Account = default(EntityRef<Account>);
			this._TeacherDetail = default(EntityRef<TeacherDetail>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeacherID", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TeacherID
		{
			get
			{
				return this._TeacherID;
			}
			set
			{
				if ((this._TeacherID != value))
				{
					if (this._TeacherDetail.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTeacherIDChanging(value);
					this.SendPropertyChanging();
					this._TeacherID = value;
					this.SendPropertyChanged("TeacherID");
					this.OnTeacherIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					if (this._Account.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Account_Teacher", Storage="_Account", ThisKey="UserID", OtherKey="UserID", IsForeignKey=true)]
		public Account Account
		{
			get
			{
				return this._Account.Entity;
			}
			set
			{
				Account previousValue = this._Account.Entity;
				if (((previousValue != value) 
							|| (this._Account.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Account.Entity = null;
						previousValue.Teachers.Remove(this);
					}
					this._Account.Entity = value;
					if ((value != null))
					{
						value.Teachers.Add(this);
						this._UserID = value.UserID;
					}
					else
					{
						this._UserID = default(string);
					}
					this.SendPropertyChanged("Account");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TeacherDetail_Teacher", Storage="_TeacherDetail", ThisKey="TeacherID", OtherKey="TeacherID", IsForeignKey=true)]
		public TeacherDetail TeacherDetail
		{
			get
			{
				return this._TeacherDetail.Entity;
			}
			set
			{
				TeacherDetail previousValue = this._TeacherDetail.Entity;
				if (((previousValue != value) 
							|| (this._TeacherDetail.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TeacherDetail.Entity = null;
						previousValue.Teachers.Remove(this);
					}
					this._TeacherDetail.Entity = value;
					if ((value != null))
					{
						value.Teachers.Add(this);
						this._TeacherID = value.TeacherID;
					}
					else
					{
						this._TeacherID = default(string);
					}
					this.SendPropertyChanged("TeacherDetail");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TeacherDetails")]
	public partial class TeacherDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TeacherID;
		
		private string _TeacherName;
		
		private System.DateTime _DOB;
		
		private EntitySet<Teacher> _Teachers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTeacherIDChanging(string value);
    partial void OnTeacherIDChanged();
    partial void OnTeacherNameChanging(string value);
    partial void OnTeacherNameChanged();
    partial void OnDOBChanging(System.DateTime value);
    partial void OnDOBChanged();
    #endregion
		
		public TeacherDetail()
		{
			this._Teachers = new EntitySet<Teacher>(new Action<Teacher>(this.attach_Teachers), new Action<Teacher>(this.detach_Teachers));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeacherID", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TeacherID
		{
			get
			{
				return this._TeacherID;
			}
			set
			{
				if ((this._TeacherID != value))
				{
					this.OnTeacherIDChanging(value);
					this.SendPropertyChanging();
					this._TeacherID = value;
					this.SendPropertyChanged("TeacherID");
					this.OnTeacherIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeacherName", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string TeacherName
		{
			get
			{
				return this._TeacherName;
			}
			set
			{
				if ((this._TeacherName != value))
				{
					this.OnTeacherNameChanging(value);
					this.SendPropertyChanging();
					this._TeacherName = value;
					this.SendPropertyChanged("TeacherName");
					this.OnTeacherNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="DateTime NOT NULL")]
		public System.DateTime DOB
		{
			get
			{
				return this._DOB;
			}
			set
			{
				if ((this._DOB != value))
				{
					this.OnDOBChanging(value);
					this.SendPropertyChanging();
					this._DOB = value;
					this.SendPropertyChanged("DOB");
					this.OnDOBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TeacherDetail_Teacher", Storage="_Teachers", ThisKey="TeacherID", OtherKey="TeacherID")]
		public EntitySet<Teacher> Teachers
		{
			get
			{
				return this._Teachers;
			}
			set
			{
				this._Teachers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Teachers(Teacher entity)
		{
			this.SendPropertyChanging();
			entity.TeacherDetail = this;
		}
		
		private void detach_Teachers(Teacher entity)
		{
			this.SendPropertyChanging();
			entity.TeacherDetail = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TheExamination")]
	public partial class TheExamination : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ExamID;
		
		private string _TestID;
		
		private string _ExamineeListID;
		
		private string _ExaminationType;
		
		private System.DateTime _CreateDate;
		
		private System.DateTime _StartDate;
		
		private System.DateTime _EndDate;
		
		private string _ExaminationName;
		
		private EntitySet<ExamineeList> _ExamineeLists;
		
		private EntityRef<TheTest> _TheTest;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnExamIDChanging(string value);
    partial void OnExamIDChanged();
    partial void OnTestIDChanging(string value);
    partial void OnTestIDChanged();
    partial void OnExamineeListIDChanging(string value);
    partial void OnExamineeListIDChanged();
    partial void OnExaminationTypeChanging(string value);
    partial void OnExaminationTypeChanged();
    partial void OnCreateDateChanging(System.DateTime value);
    partial void OnCreateDateChanged();
    partial void OnStartDateChanging(System.DateTime value);
    partial void OnStartDateChanged();
    partial void OnEndDateChanging(System.DateTime value);
    partial void OnEndDateChanged();
    partial void OnExaminationNameChanging(string value);
    partial void OnExaminationNameChanged();
    #endregion
		
		public TheExamination()
		{
			this._ExamineeLists = new EntitySet<ExamineeList>(new Action<ExamineeList>(this.attach_ExamineeLists), new Action<ExamineeList>(this.detach_ExamineeLists));
			this._TheTest = default(EntityRef<TheTest>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExamID", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ExamID
		{
			get
			{
				return this._ExamID;
			}
			set
			{
				if ((this._ExamID != value))
				{
					this.OnExamIDChanging(value);
					this.SendPropertyChanging();
					this._ExamID = value;
					this.SendPropertyChanged("ExamID");
					this.OnExamIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TestID", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string TestID
		{
			get
			{
				return this._TestID;
			}
			set
			{
				if ((this._TestID != value))
				{
					if (this._TheTest.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTestIDChanging(value);
					this.SendPropertyChanging();
					this._TestID = value;
					this.SendPropertyChanged("TestID");
					this.OnTestIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExamineeListID", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string ExamineeListID
		{
			get
			{
				return this._ExamineeListID;
			}
			set
			{
				if ((this._ExamineeListID != value))
				{
					this.OnExamineeListIDChanging(value);
					this.SendPropertyChanging();
					this._ExamineeListID = value;
					this.SendPropertyChanged("ExamineeListID");
					this.OnExamineeListIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExaminationType", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string ExaminationType
		{
			get
			{
				return this._ExaminationType;
			}
			set
			{
				if ((this._ExaminationType != value))
				{
					this.OnExaminationTypeChanging(value);
					this.SendPropertyChanging();
					this._ExaminationType = value;
					this.SendPropertyChanged("ExaminationType");
					this.OnExaminationTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime NOT NULL")]
		public System.DateTime CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartDate", DbType="DateTime NOT NULL")]
		public System.DateTime StartDate
		{
			get
			{
				return this._StartDate;
			}
			set
			{
				if ((this._StartDate != value))
				{
					this.OnStartDateChanging(value);
					this.SendPropertyChanging();
					this._StartDate = value;
					this.SendPropertyChanged("StartDate");
					this.OnStartDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDate", DbType="DateTime NOT NULL")]
		public System.DateTime EndDate
		{
			get
			{
				return this._EndDate;
			}
			set
			{
				if ((this._EndDate != value))
				{
					this.OnEndDateChanging(value);
					this.SendPropertyChanging();
					this._EndDate = value;
					this.SendPropertyChanged("EndDate");
					this.OnEndDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExaminationName", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string ExaminationName
		{
			get
			{
				return this._ExaminationName;
			}
			set
			{
				if ((this._ExaminationName != value))
				{
					this.OnExaminationNameChanging(value);
					this.SendPropertyChanging();
					this._ExaminationName = value;
					this.SendPropertyChanged("ExaminationName");
					this.OnExaminationNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TheExamination_ExamineeList", Storage="_ExamineeLists", ThisKey="ExamID", OtherKey="ExamineeListID")]
		public EntitySet<ExamineeList> ExamineeLists
		{
			get
			{
				return this._ExamineeLists;
			}
			set
			{
				this._ExamineeLists.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TheTest_TheExamination", Storage="_TheTest", ThisKey="TestID", OtherKey="TestID", IsForeignKey=true)]
		public TheTest TheTest
		{
			get
			{
				return this._TheTest.Entity;
			}
			set
			{
				TheTest previousValue = this._TheTest.Entity;
				if (((previousValue != value) 
							|| (this._TheTest.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TheTest.Entity = null;
						previousValue.TheExaminations.Remove(this);
					}
					this._TheTest.Entity = value;
					if ((value != null))
					{
						value.TheExaminations.Add(this);
						this._TestID = value.TestID;
					}
					else
					{
						this._TestID = default(string);
					}
					this.SendPropertyChanged("TheTest");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ExamineeLists(ExamineeList entity)
		{
			this.SendPropertyChanging();
			entity.TheExamination = this;
		}
		
		private void detach_ExamineeLists(ExamineeList entity)
		{
			this.SendPropertyChanging();
			entity.TheExamination = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TheQuestion")]
	public partial class TheQuestion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _QuestionID;
		
		private string _QuestionLevel;
		
		private string _QuestionType;
		
		private string _QuestionContent;
		
		private string _ChoiceA;
		
		private string _ChoiceB;
		
		private string _ChoiceC;
		
		private string _ChoiceD;
		
		private string _ChoiceE;
		
		private string _ChoiceF;
		
		private string _Answer;
		
		private EntitySet<QuestionList> _QuestionLists;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnQuestionIDChanging(string value);
    partial void OnQuestionIDChanged();
    partial void OnQuestionLevelChanging(string value);
    partial void OnQuestionLevelChanged();
    partial void OnQuestionTypeChanging(string value);
    partial void OnQuestionTypeChanged();
    partial void OnQuestionContentChanging(string value);
    partial void OnQuestionContentChanged();
    partial void OnChoiceAChanging(string value);
    partial void OnChoiceAChanged();
    partial void OnChoiceBChanging(string value);
    partial void OnChoiceBChanged();
    partial void OnChoiceCChanging(string value);
    partial void OnChoiceCChanged();
    partial void OnChoiceDChanging(string value);
    partial void OnChoiceDChanged();
    partial void OnChoiceEChanging(string value);
    partial void OnChoiceEChanged();
    partial void OnChoiceFChanging(string value);
    partial void OnChoiceFChanged();
    partial void OnAnswerChanging(string value);
    partial void OnAnswerChanged();
    #endregion
		
		public TheQuestion()
		{
			this._QuestionLists = new EntitySet<QuestionList>(new Action<QuestionList>(this.attach_QuestionLists), new Action<QuestionList>(this.detach_QuestionLists));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuestionID", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string QuestionID
		{
			get
			{
				return this._QuestionID;
			}
			set
			{
				if ((this._QuestionID != value))
				{
					this.OnQuestionIDChanging(value);
					this.SendPropertyChanging();
					this._QuestionID = value;
					this.SendPropertyChanged("QuestionID");
					this.OnQuestionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuestionLevel", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string QuestionLevel
		{
			get
			{
				return this._QuestionLevel;
			}
			set
			{
				if ((this._QuestionLevel != value))
				{
					this.OnQuestionLevelChanging(value);
					this.SendPropertyChanging();
					this._QuestionLevel = value;
					this.SendPropertyChanged("QuestionLevel");
					this.OnQuestionLevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuestionType", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string QuestionType
		{
			get
			{
				return this._QuestionType;
			}
			set
			{
				if ((this._QuestionType != value))
				{
					this.OnQuestionTypeChanging(value);
					this.SendPropertyChanging();
					this._QuestionType = value;
					this.SendPropertyChanged("QuestionType");
					this.OnQuestionTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuestionContent", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string QuestionContent
		{
			get
			{
				return this._QuestionContent;
			}
			set
			{
				if ((this._QuestionContent != value))
				{
					this.OnQuestionContentChanging(value);
					this.SendPropertyChanging();
					this._QuestionContent = value;
					this.SendPropertyChanged("QuestionContent");
					this.OnQuestionContentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChoiceA", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string ChoiceA
		{
			get
			{
				return this._ChoiceA;
			}
			set
			{
				if ((this._ChoiceA != value))
				{
					this.OnChoiceAChanging(value);
					this.SendPropertyChanging();
					this._ChoiceA = value;
					this.SendPropertyChanged("ChoiceA");
					this.OnChoiceAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChoiceB", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string ChoiceB
		{
			get
			{
				return this._ChoiceB;
			}
			set
			{
				if ((this._ChoiceB != value))
				{
					this.OnChoiceBChanging(value);
					this.SendPropertyChanging();
					this._ChoiceB = value;
					this.SendPropertyChanged("ChoiceB");
					this.OnChoiceBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChoiceC", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string ChoiceC
		{
			get
			{
				return this._ChoiceC;
			}
			set
			{
				if ((this._ChoiceC != value))
				{
					this.OnChoiceCChanging(value);
					this.SendPropertyChanging();
					this._ChoiceC = value;
					this.SendPropertyChanged("ChoiceC");
					this.OnChoiceCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChoiceD", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string ChoiceD
		{
			get
			{
				return this._ChoiceD;
			}
			set
			{
				if ((this._ChoiceD != value))
				{
					this.OnChoiceDChanging(value);
					this.SendPropertyChanging();
					this._ChoiceD = value;
					this.SendPropertyChanged("ChoiceD");
					this.OnChoiceDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChoiceE", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string ChoiceE
		{
			get
			{
				return this._ChoiceE;
			}
			set
			{
				if ((this._ChoiceE != value))
				{
					this.OnChoiceEChanging(value);
					this.SendPropertyChanging();
					this._ChoiceE = value;
					this.SendPropertyChanged("ChoiceE");
					this.OnChoiceEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChoiceF", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string ChoiceF
		{
			get
			{
				return this._ChoiceF;
			}
			set
			{
				if ((this._ChoiceF != value))
				{
					this.OnChoiceFChanging(value);
					this.SendPropertyChanging();
					this._ChoiceF = value;
					this.SendPropertyChanged("ChoiceF");
					this.OnChoiceFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Answer", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Answer
		{
			get
			{
				return this._Answer;
			}
			set
			{
				if ((this._Answer != value))
				{
					this.OnAnswerChanging(value);
					this.SendPropertyChanging();
					this._Answer = value;
					this.SendPropertyChanged("Answer");
					this.OnAnswerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TheQuestion_QuestionList", Storage="_QuestionLists", ThisKey="QuestionID", OtherKey="QuestionID")]
		public EntitySet<QuestionList> QuestionLists
		{
			get
			{
				return this._QuestionLists;
			}
			set
			{
				this._QuestionLists.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_QuestionLists(QuestionList entity)
		{
			this.SendPropertyChanging();
			entity.TheQuestion = this;
		}
		
		private void detach_QuestionLists(QuestionList entity)
		{
			this.SendPropertyChanging();
			entity.TheQuestion = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TheResult")]
	public partial class TheResult : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TestID;
		
		private string _UserID;
		
		private int _Score;
		
		private EntityRef<Account> _Account;
		
		private EntityRef<TheTest> _TheTest;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTestIDChanging(string value);
    partial void OnTestIDChanged();
    partial void OnUserIDChanging(string value);
    partial void OnUserIDChanged();
    partial void OnScoreChanging(int value);
    partial void OnScoreChanged();
    #endregion
		
		public TheResult()
		{
			this._Account = default(EntityRef<Account>);
			this._TheTest = default(EntityRef<TheTest>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TestID", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TestID
		{
			get
			{
				return this._TestID;
			}
			set
			{
				if ((this._TestID != value))
				{
					if ((this._Account.HasLoadedOrAssignedValue || this._TheTest.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTestIDChanging(value);
					this.SendPropertyChanging();
					this._TestID = value;
					this.SendPropertyChanged("TestID");
					this.OnTestIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Score", DbType="Int NOT NULL")]
		public int Score
		{
			get
			{
				return this._Score;
			}
			set
			{
				if ((this._Score != value))
				{
					this.OnScoreChanging(value);
					this.SendPropertyChanging();
					this._Score = value;
					this.SendPropertyChanged("Score");
					this.OnScoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Account_TheResult", Storage="_Account", ThisKey="TestID", OtherKey="UserID", IsForeignKey=true)]
		public Account Account
		{
			get
			{
				return this._Account.Entity;
			}
			set
			{
				Account previousValue = this._Account.Entity;
				if (((previousValue != value) 
							|| (this._Account.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Account.Entity = null;
						previousValue.TheResults.Remove(this);
					}
					this._Account.Entity = value;
					if ((value != null))
					{
						value.TheResults.Add(this);
						this._TestID = value.UserID;
					}
					else
					{
						this._TestID = default(string);
					}
					this.SendPropertyChanged("Account");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TheTest_TheResult", Storage="_TheTest", ThisKey="TestID", OtherKey="TestID", IsForeignKey=true)]
		public TheTest TheTest
		{
			get
			{
				return this._TheTest.Entity;
			}
			set
			{
				TheTest previousValue = this._TheTest.Entity;
				if (((previousValue != value) 
							|| (this._TheTest.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TheTest.Entity = null;
						previousValue.TheResults.Remove(this);
					}
					this._TheTest.Entity = value;
					if ((value != null))
					{
						value.TheResults.Add(this);
						this._TestID = value.TestID;
					}
					else
					{
						this._TestID = default(string);
					}
					this.SendPropertyChanged("TheTest");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TheTest")]
	public partial class TheTest : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TestID;
		
		private string _ListID;
		
		private EntitySet<TheExamination> _TheExaminations;
		
		private EntitySet<TheResult> _TheResults;
		
		private EntityRef<QuestionList> _QuestionList;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTestIDChanging(string value);
    partial void OnTestIDChanged();
    partial void OnListIDChanging(string value);
    partial void OnListIDChanged();
    #endregion
		
		public TheTest()
		{
			this._TheExaminations = new EntitySet<TheExamination>(new Action<TheExamination>(this.attach_TheExaminations), new Action<TheExamination>(this.detach_TheExaminations));
			this._TheResults = new EntitySet<TheResult>(new Action<TheResult>(this.attach_TheResults), new Action<TheResult>(this.detach_TheResults));
			this._QuestionList = default(EntityRef<QuestionList>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TestID", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TestID
		{
			get
			{
				return this._TestID;
			}
			set
			{
				if ((this._TestID != value))
				{
					this.OnTestIDChanging(value);
					this.SendPropertyChanging();
					this._TestID = value;
					this.SendPropertyChanged("TestID");
					this.OnTestIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ListID", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string ListID
		{
			get
			{
				return this._ListID;
			}
			set
			{
				if ((this._ListID != value))
				{
					if (this._QuestionList.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnListIDChanging(value);
					this.SendPropertyChanging();
					this._ListID = value;
					this.SendPropertyChanged("ListID");
					this.OnListIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TheTest_TheExamination", Storage="_TheExaminations", ThisKey="TestID", OtherKey="TestID")]
		public EntitySet<TheExamination> TheExaminations
		{
			get
			{
				return this._TheExaminations;
			}
			set
			{
				this._TheExaminations.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TheTest_TheResult", Storage="_TheResults", ThisKey="TestID", OtherKey="TestID")]
		public EntitySet<TheResult> TheResults
		{
			get
			{
				return this._TheResults;
			}
			set
			{
				this._TheResults.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QuestionList_TheTest", Storage="_QuestionList", ThisKey="ListID", OtherKey="ListID", IsForeignKey=true)]
		public QuestionList QuestionList
		{
			get
			{
				return this._QuestionList.Entity;
			}
			set
			{
				QuestionList previousValue = this._QuestionList.Entity;
				if (((previousValue != value) 
							|| (this._QuestionList.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QuestionList.Entity = null;
						previousValue.TheTests.Remove(this);
					}
					this._QuestionList.Entity = value;
					if ((value != null))
					{
						value.TheTests.Add(this);
						this._ListID = value.ListID;
					}
					else
					{
						this._ListID = default(string);
					}
					this.SendPropertyChanged("QuestionList");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TheExaminations(TheExamination entity)
		{
			this.SendPropertyChanging();
			entity.TheTest = this;
		}
		
		private void detach_TheExaminations(TheExamination entity)
		{
			this.SendPropertyChanging();
			entity.TheTest = null;
		}
		
		private void attach_TheResults(TheResult entity)
		{
			this.SendPropertyChanging();
			entity.TheTest = this;
		}
		
		private void detach_TheResults(TheResult entity)
		{
			this.SendPropertyChanging();
			entity.TheTest = null;
		}
	}
}
#pragma warning restore 1591
