<?xml version="1.0" encoding="utf-8"?><Database Name="ExaminationManagement" Class="ExaminationManagementDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-MSIGV72\SQLEXPRESS;Initial Catalog=ExaminationManagement;User ID=sa;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False" SettingsObjectName="ExaminationManagement.Properties.Settings" SettingsPropertyName="ExaminationManagementConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TheTest" Member="TheTests">
    <Type Name="TheTest">
      <Column Name="testID" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="listID" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Association Name="TheTest_TheExamination" Member="TheExaminations" ThisKey="testID" OtherKey="testID" Type="TheExamination" />
      <Association Name="TheTest_TheResult" Member="TheResults" ThisKey="testID" OtherKey="testID" Type="TheResult" />
      <Association Name="QuestionList_TheTest" Member="QuestionList" ThisKey="listID" OtherKey="listID" Type="QuestionList" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Account" Member="Accounts">
    <Type Name="Account">
      <Column Name="userID" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="permission" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="reg_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Account_ExamineeList" Member="ExamineeLists" ThisKey="userID" OtherKey="userID" Type="ExamineeList" />
      <Association Name="Account_TheResult" Member="TheResults" ThisKey="userID" OtherKey="testID" Type="TheResult" />
      <Association Name="Student_Account" Member="Student" ThisKey="userID" OtherKey="userID" Type="Student" IsForeignKey="true" />
      <Association Name="Teacher_Account" Member="Teacher" ThisKey="userID" OtherKey="userID" Type="Teacher" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ExamineeList" Member="ExamineeLists">
    <Type Name="ExamineeList">
      <Column Name="exListID" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="userID" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="exam_type" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Association Name="Account_ExamineeList" Member="Account" ThisKey="userID" OtherKey="userID" Type="Account" IsForeignKey="true" />
      <Association Name="TheExamination_ExamineeList" Member="TheExamination" ThisKey="exListID" OtherKey="examID" Type="TheExamination" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QuestionList" Member="QuestionLists">
    <Type Name="QuestionList">
      <Column Name="listID" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="questionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="QuestionList_TheTest" Member="TheTests" ThisKey="listID" OtherKey="listID" Type="TheTest" />
      <Association Name="TheQuestion_QuestionList" Member="TheQuestion" ThisKey="questionID" OtherKey="questionID" Type="TheQuestion" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Student" Member="Students">
    <Type Name="Student">
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="userID" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="dob" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="classID" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Association Name="Student_Account" Member="Account" ThisKey="userID" OtherKey="userID" Type="Account" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.Teacher" Member="Teachers">
    <Type Name="Teacher">
      <Column Name="userID" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="dob" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Teacher_Account" Member="Account" ThisKey="userID" OtherKey="userID" Type="Account" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.TheExamination" Member="TheExaminations">
    <Type Name="TheExamination">
      <Column Name="examID" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="testID" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="exam_type" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="date_time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="exListID" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Association Name="TheExamination_ExamineeList" Member="ExamineeLists" ThisKey="examID" OtherKey="exListID" Type="ExamineeList" />
      <Association Name="TheTest_TheExamination" Member="TheTest" ThisKey="testID" OtherKey="testID" Type="TheTest" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TheQuestion" Member="TheQuestions">
    <Type Name="TheQuestion">
      <Column Name="questionID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[level]" Member="level" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="content" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="choiceA" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="choiceB" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="choiceC" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="choiceD" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="choiceE" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="choiceF" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="answer" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="TheQuestion_QuestionList" Member="QuestionLists" ThisKey="questionID" OtherKey="questionID" Type="QuestionList" />
    </Type>
  </Table>
  <Table Name="dbo.TheResult" Member="TheResults">
    <Type Name="TheResult">
      <Column Name="testID" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="userID" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="the_score" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Account_TheResult" Member="Account" ThisKey="testID" OtherKey="userID" Type="Account" IsForeignKey="true" />
      <Association Name="TheTest_TheResult" Member="TheTest" ThisKey="testID" OtherKey="testID" Type="TheTest" IsForeignKey="true" />
    </Type>
  </Table>
</Database>